<?php
//    MyDMS. Document Management System
//    Copyright (C) 2002-2005  Markus Westphal
//    Copyright (C) 2006-2008 Malcolm Cowe
//    Copyright (C) 2010 Matteo Lucarelli
//    Copyright (C) 2011-2013 Uwe Steinmann
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program; if not, write to the Free Software
//    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
//
//    Translators: Admin (2561), archonwang (3), dgrutsch (9), netixw (14)

$text = array(
'2_factor_auth' => '二要素認証',
'2_factor_auth_code' => '二次認証コード',
'2_factor_auth_info' => 'このシステムは二要素認証を必須としています。モバイル端末に認証アプリが必要です。下記に2つのQRコードがあります。右側が現在のシークレット、左側で新しいシークレットを設定できます。新しいシークレットを設定した場合は、使用する認証アプリで再スキャンしてください（例: andOTP）。',
'2_fact_auth_current_secret' => '現在のシークレット',
'2_fact_auth_new_secret' => '新しいシークレット',
'2_fact_auth_qrcode' => 'QRコード',
'2_fact_auth_secret' => 'シークレット',
'abbr_day' => '日',
'abbr_hour' => '時',
'abbr_minute' => '分',
'abbr_month' => '月',
'abbr_second' => '秒',
'abbr_week' => '週',
'abbr_year' => '年',
'accept' => '承認',
'access_control' => 'アクセス制御',
'access_control_is_off' => '高度なアクセス制御は無効です',
'access_denied' => 'アクセスが拒否されました。',
'access_inheritance' => 'アクセス継承',
'access_mode' => 'アクセスモード',
'access_mode_all' => 'すべての権限',
'access_mode_none' => 'アクセスなし',
'access_mode_read' => '読み取り権限',
'access_mode_readwrite' => '読み書き権限',
'according_settings' => '設定に従う',
'action' => '操作',
'actions' => '操作一覧',
'action_approve' => '承認',
'action_complete' => '完了',
'action_is_complete' => '完了済み',
'action_is_not_complete' => '未完了',
'action_reject' => '却下',
'action_review' => 'レビュー',
'action_revise' => '修正',
'add' => '追加',
'add_approval' => '承認を追加',
'add_attrdefgroup' => '新しい属性グループを追加',
'add_document' => '文書を追加',
'add_document_link' => 'リンクを追加',
'add_document_notify' => '通知を設定',
'add_doc_reviewer_approver_warning' => '注: レビュー担当者や承認者が設定されていない場合、文書は自動的に公開済みとしてマークされます。',
'add_doc_workflow_warning' => '注: ワークフローが設定されていない場合、文書は自動的に公開済みとしてマークされます。',
'add_event' => 'イベントを追加',
'add_group' => '新しいグループを追加',
'add_member' => 'メンバーを追加',
'add_multiple_documents' => '複数の文書を追加',
'add_multiple_files' => '複数ファイルを追加（ファイル名を文書名として使用）',
'add_receipt' => '受領確認',
'add_review' => 'レビューを追加',
'add_revision' => '改訂を追加',
'add_role' => '新しい役割を追加',
'add_subfolder' => 'サブフォルダを追加',
'add_task' => 'このクラスの新しいタスクを追加',
'add_to_clipboard' => 'クリップボードに追加',
'add_to_transmittal' => '送付リストに追加',
'add_transmittal' => '送付リストを追加',
'add_user' => '新しいユーザーを追加',
'add_user_to_group' => 'ユーザーをグループに追加',
'add_workflow' => '新しいワークフローを追加',
'add_workflow_action' => '新しいワークフローアクションを追加',
'add_workflow_state' => '新しいワークフローステートを追加',
'admin' => '管理者',
'admin_tools' => '管理ツール',
'all' => 'すべて',
'all_categories' => 'すべてのカテゴリ',
'all_documents' => 'すべての文書',
'all_pages' => 'すべてのページ',
'all_users' => 'すべてのユーザー',
'already_subscribed' => 'すでに登録済み',
'and' => 'および',
'any_value_set' => '任意の値',
'apikey' => 'APIキー',
'apply' => '適用',
'approvals_accepted' => '[no_approvals] 件の承認がすでに承認済み',
'approvals_accepted_latest' => '(最新バージョンで [no_approvals] 件承認済み)',
'approvals_and_reviews_accepted' => '[no_approvals] 件の承認と [no_reviews] 件のレビューが承認済み',
'approvals_and_reviews_not_touched' => '[no_approvals] 件の承認と [no_reviews] 件のレビューは未処理',
'approvals_and_reviews_rejected' => '[no_approvals] 件の承認と [no_reviews] 件のレビューが却下済み',
'approvals_not_touched' => '[no_approvals] 件の承認は未処理',
'approvals_not_touched_latest' => '(最新バージョンで [no_approvals] 件未処理)',
'approvals_rejected' => '[no_approvals] 件の承認が却下済み',
'approvals_rejected_latest' => '(最新バージョンで [no_approvals] 件却下済み)',
'approvals_without_group' => 'グループなしの承認',
'approvals_without_user' => 'ユーザーなしの承認',
'approval_deletion_email' => '承認リクエスト削除',
'approval_deletion_email_body' => '承認リクエストが削除されました

文書: [name]
バージョン: [version]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'approval_deletion_email_body_html' => '<p>承認リクエストが削除されました</p>

<p>文書: [name]<br />
バージョン: [version]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'approval_deletion_email_subject' => '[sitename]: [name] - 承認リクエスト削除',
'approval_file' => 'ファイル',
'approval_group' => '承認グループ',
'approval_log' => '承認ログ',
'approval_request_email' => '承認リクエスト',
'approval_request_email_body' => '承認リクエスト

文書: [name]
バージョン: [version]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'approval_request_email_body_html' => '<p>承認リクエスト</p>

<p>文書: [name]<br />
バージョン: [version]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'approval_request_email_subject' => '[sitename]: [name] - 承認リクエスト',
'approval_status' => '承認ステータス',
'approval_submit_email' => '',
'approval_submit_email_body' => '文書承認

文書: [name]
バージョン: [version]
親フォルダ: [folder_path]
ステータス: [status]
コメント: [comment]
ユーザー: [username]
URL: [url]',
'approval_submit_email_body_html' => '<p>文書承認</p>

<p>文書: [name]<br />
バージョン: [version]<br />
親フォルダ: [folder_path]<br />
ステータス: [status]<br />
コメント: [comment]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'approval_submit_email_subject' => '[sitename]: [name] - 承認済み',
'approval_summary' => '承認概要',
'approval_update_failed' => '承認ステータスの更新中にエラーが発生しました',
'approvers' => '承認者',
'approver_already_assigned' => 'このユーザーはすでに承認者として割り当てられています',
'approver_already_removed' => '承認者はすでに削除されているか、承認済みです',
'april' => '4月',
'archive' => 'アーカイブ',
'archive_creation' => 'アーカイブ作成',
'archive_creation_warning' => 'この操作により、DMSフォルダ内の全ファイルを含むアーカイブを作成できます。作成後、サーバーのデータフォルダに保存されます。<br>警告: 人間が読める形式で作成されたアーカイブはサーバーバックアップとして使用できません。',
'ar_EG' => 'アラビア語',
'assign_approvers' => '承認者を割り当てる',
'assign_recipients' => '受信者を割り当てる',
'assign_reviewers' => 'レビュー担当者を割り当てる',
'assign_user_property_to' => 'ユーザー属性を割り当てる',
'assumed_released' => '自動的に公開済みとみなす',
'attrdefgroup_management' => '属性グループ管理',
'attrdefgrp_show_detail' => '詳細表示',
'attrdefgrp_show_list' => '一覧表示',
'attrdefgrp_show_search' => '検索',
'attrdefgrp_show_searchlist' => '検索結果表示',
'attrdef_exists' => '属性定義はすでに存在します',
'attrdef_info' => '情報',
'attrdef_invalid_regex' => '正規表現が無効です',
'attrdef_in_use' => '属性定義はまだ使用中です',
'attrdef_management' => '属性定義管理',
'attrdef_maxvalues' => '最大値の数',
'attrdef_minvalues' => '最小値の数',
'attrdef_minvalues_help' => '属性が必須の場合は1に設定してください',
'attrdef_min_greater_max' => '最小値が最大値より大きいです',
'attrdef_multiple' => '複数値を許可',
'attrdef_multiple_but_doc_or_folder' => '文書またはフォルダ属性は複数値を持てません',
'attrdef_multiple_needs_valueset' => '複数の値を持つ属性定義には値セットが必要です',
'attrdef_must_be_multiple' => '属性は複数の値を持つ必要がありますが、複数値として設定されていません',
'attrdef_name' => '名前',
'attrdef_noname' => '属性定義の名前がありません',
'attrdef_objtype' => 'オブジェクトタイプ',
'attrdef_regex' => '正規表現',
'attrdef_regex_help' => 'タイプが文字列の場合、属性値が一致しなければならない正規表現。',
'attrdef_type' => 'タイプ',
'attrdef_type_boolean' => '真偽値',
'attrdef_type_date' => '日付',
'attrdef_type_document' => 'ドキュメント',
'attrdef_type_email' => 'メールアドレス',
'attrdef_type_float' => '浮動小数点数',
'attrdef_type_folder' => 'フォルダー',
'attrdef_type_group' => 'グループ',
'attrdef_type_int' => '整数',
'attrdef_type_string' => '文字列',
'attrdef_type_url' => 'URL',
'attrdef_type_user' => 'ユーザー',
'attrdef_valueset' => '値のセット',
'attrdef_valueset_help' => '任意の文字で区切られた値のリスト。この文字は文字列の最初の文字である必要があります。例: #はい#いいえ#たぶん',
'attributes' => '属性',
'attribute_changed_email_body' => '属性が変更されました

ドキュメント: [name]
バージョン: [version]
属性: [attribute_name]
旧値: [attribute_old_value]
新値: [attribute_new_value]
親フォルダー: [folder_path]
ユーザー: [username]
URL: [url]',
'attribute_changed_email_body_html' => '<p>属性が変更されました</p>

<p>ドキュメント: [name]<br />
バージョン: [version]<br />
属性: [attribute_name]<br />
旧値: [attribute_old_value]<br />
新値: [attribute_new_value]<br />
親フォルダー: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'attribute_changed_email_subject' => '[sitename]: [name] - 属性が変更されました',
'attribute_count' => '使用回数',
'attribute_value' => '属性値',
'attribute_value_not_in_valueset' => '値が値セットに含まれていません',
'attr_malformed_boolean' => '属性「[attrname]」の値「[value]」は有効な真偽値ではありません。',
'attr_malformed_date' => '属性「[attrname]」の値「[value]」は有効な日付ではありません。',
'attr_malformed_email' => '属性「[attrname]」の値「[value]」は有効なメールアドレスではありません。',
'attr_malformed_float' => '属性「[attrname]」の値「[value]」は有効な浮動小数点数ではありません。',
'attr_malformed_int' => '属性「[attrname]」の値「[value]」は有効な整数ではありません。',
'attr_malformed_url' => '属性「[attrname]」の値「[value]」は有効なURLではありません。',
'attr_max_values' => '属性 [attrname] に必要な最大値数を超えています。',
'attr_min_values' => '属性 [attrname] に必要な最小値数に達していません。',
'attr_not_in_valueset' => '属性 [attrname] の値「[value]」は値セットに含まれていません。',
'attr_no_regex_match' => '属性 [attrname] の値「[value]」は正規表現「[regex]」に一致しません。',
'attr_validation_error' => '属性 [attrname] の値「[value]」は無効です。',
'at_least_n_users_of_group' => '[group] のユーザーが少なくとも [number_of_users] 人必要です',
'august' => '8月',
'authentication' => '認証',
'authentication_failed' => '認証に失敗しました',
'author' => '作成者',
'automatic_status_update' => 'ステータスの自動変更',
'back' => '戻る',
'backup_list' => '既存のバックアップ',
'backup_log_management' => 'バックアップ／ログ管理',
'backup_remove' => 'バックアップファイルを削除',
'backup_tools' => 'バックアップツール',
'batch_add_approver' => '承認者を追加',
'batch_add_approver_msg' => '[count] 件のドキュメントに承認者「[name]」を追加しました。',
'batch_add_category_msg' => '[count] 件のドキュメントに新しいカテゴリ「[catname]」を追加しました。',
'batch_add_reviewer' => 'レビュアーを追加',
'batch_add_reviewer_msg' => '[count] 件のドキュメントにレビュアー「[name]」を追加しました。',
'batch_change_category' => 'カテゴリを変更',
'batch_change_owner' => '所有者を変更',
'batch_export' => 'エクスポート',
'batch_new_owner_msg' => '[count] 件のドキュメントの所有者を変更しました。',
'batch_operation' => '一括操作',
'batch_operation_result' => '一括操作の結果',
'batch_remove_category' => 'カテゴリを削除',
'batch_remove_category_msg' => '[count] 件のドキュメントからカテゴリ「[catname]」を削除しました。',
'between' => '～の間',
'bg_BG' => 'ブルガリア語',
'browse' => '参照',
'calendar' => 'カレンダー',
'calendar_events_mail_subject' => '今後のイベント',
'calendar_week' => 'カレンダー週',
'cancel' => 'キャンセル',
'cancel_checkout' => 'チェックアウトを取り消す',
'cancel_checkout_document' => 'チェックアウトを取り消す',
'cancel_checkout_warning' => 'チェックアウトしたファイルが変更されていてもチェックアウトを取り消すことができます。その場合、チェックアウト領域からファイルが削除され、変更内容は失われます。',
'cannot_assign_invalid_state' => '廃止済みまたは却下されたドキュメントは変更できません',
'cannot_change_final_states' => '警告: 却下、期限切れ、レビューまたは承認待ちのドキュメントのステータスは変更できません',
'cannot_delete_user' => 'ユーザーを削除できません',
'cannot_delete_yourself' => '自分自身を削除することはできません',
'cannot_move_root' => 'エラー: ルートフォルダーを移動できません。',
'cannot_retrieve_approval_snapshot' => 'このドキュメントバージョンの承認ステータススナップショットを取得できません。',
'cannot_retrieve_review_snapshot' => 'このドキュメントバージョンのレビューステータススナップショットを取得できません。',
'cannot_revapp_expired_docs' => 'ドキュメントは期限切れのため、レビューや承認はできません。',
'cannot_rm_root' => 'エラー: ルートフォルダーを削除できません。',
'cannot_transfer_your_objects' => '自分自身のオブジェクトを移譲することはできません',
'categories' => 'カテゴリ',
'categories_loading' => 'カテゴリ一覧を読み込んでいます。しばらくお待ちください…',
'category' => 'カテゴリ',
'category_exists' => 'カテゴリはすでに存在します。',
'category_filter' => 'カテゴリ',
'category_info' => '情報',
'category_in_use' => 'このカテゴリは現在ドキュメントで使用されています。',
'category_noname' => 'カテゴリ名が指定されていません。',
'ca_ES' => 'カタルーニャ語',
'changelog_loading' => '変更履歴を読み込んでいます。しばらくお待ちください…',
'change_assignments' => 'レビュアー／承認者を設定',
'change_password' => 'パスワードを変更',
'change_password_message' => 'パスワードが変更されました。',
'change_recipients' => '受信者を設定',
'change_revisors' => 'リビジョン担当を設定',
'change_status' => 'ステータスを変更',
'charts' => 'チャート',
'chart_docsaccumulated_title' => 'ドキュメント数',
'chart_docspercategory_title' => 'カテゴリごとのドキュメント数',
'chart_docspermimetype_title' => 'MIMEタイプごとのドキュメント数',
'chart_docspermonth_title' => '月ごとの新規ドキュメント数',
'chart_docsperstatus_title' => 'ステータスごとのドキュメント数',
'chart_docsperuser_title' => 'ユーザーごとのドキュメント数',
'chart_foldersperuser_title' => 'ユーザーごとのフォルダー数',
'chart_selection' => 'チャートを選択',
'chart_sizepermonth_title' => '月ごとのディスク使用量',
'chart_sizeperuser_title' => 'ユーザーごとのディスク使用量',
'checkedout_file_has_different_version' => 'チェックアウトされたバージョンは現在のバージョンと一致しません。チェックインしてもドキュメントは更新されません。',
'checkedout_file_has_disappeared' => 'チェックアウトしたドキュメントのファイルが消えています。チェックインはできません。',
'checkedout_file_is_unchanged' => 'チェックアウトしたドキュメントのファイルは変更されていません。チェックインはできません。変更する予定がない場合は、チェックアウト状態をリセットできます。',
'checkin_document' => 'チェックイン',
'checkoutpath_does_not_exist' => 'チェックアウトパスが存在しません',
'checkout_cancel_confirm' => 'チェックアウトを取り消してもよろしいですか？',
'checkout_document' => 'チェックアウト',
'checkout_is_disabled' => '設定でドキュメントのチェックアウトが無効化されています。',
'check_directory_layout' => 'ディレクトリ構成を確認',
'check_failed' => '失敗',
'check_notification_filter' => '通知フィルターを確認',
'check_passed' => '成功',
'check_secure_installation' => '安全なインストールを確認',
'choose_attrdef' => '属性定義を選択してください',
'choose_attrdefgroup' => '属性グループを選択',
'choose_category' => 'カテゴリを選択してください',
'choose_group' => 'グループを選択',
'choose_link_type' => 'リンクタイプを選択',
'choose_role' => '役割を選択',
'choose_target_category' => '対象カテゴリを選択',
'choose_target_document' => '対象ドキュメントを選択',
'choose_target_file' => '対象ファイルを選択',
'choose_target_folder' => '対象フォルダーを選択',
'choose_user' => 'ユーザーを選択',
'choose_workflow' => 'ワークフローを選択',
'choose_workflow_action' => 'ワークフローアクションを選択',
'choose_workflow_state' => 'ワークフローステートを選択',
'class_finfo_missing' => 'ファイルアップロード時のMIMEタイプ判定にクラス finfo が使用されます。',
'class_name' => 'クラス名',
'clear_cache' => 'キャッシュをクリア',
'clear_clipboard' => 'クリップボードをクリア',
'clear_password' => 'パスワードをクリア',
'click_to_expand_filter_results' => 'クリックしてフィルター結果を展開',
'clipboard' => 'クリップボード',
'close' => '閉じる',
'color' => '色',
'command' => 'コマンド',
'comment' => 'コメント',
'comment_changed_email' => '',
'comment_for_current_version' => 'バージョンコメント',
'configure_extension' => '拡張機能を設定',
'confirm_add_approver' => '選択したドキュメントに承認者を追加することを確認してください。',
'confirm_add_reviewer' => '選択したドキュメントにレビュアーを追加することを確認してください。',
'confirm_change_category' => '選択したドキュメントのカテゴリを変更することを確認してください。',
'confirm_change_owner' => '選択したオブジェクトの所有者を変更することを確認してください。',
'confirm_clear_cache' => '本当にキャッシュをクリアしますか？これにより、事前計算されたプレビュー画像やJavaScriptその他のファイルが削除されます。',
'confirm_create_fulltext_index' => 'はい、全文索引を再作成します！',
'confirm_move_document' => 'ドキュメントを移動することを確認してください。',
'confirm_move_folder' => 'フォルダーを移動することを確認してください。',
'confirm_pwd' => 'パスワード（確認）',
'confirm_rm_attr_value' => '本当にこの属性値を削除しますか？',
'confirm_rm_backup' => '本当にファイル「[arkname]」を削除しますか？<br>注意: この操作は元に戻せません。',
'confirm_rm_document' => '本当にドキュメント「[documentname]」を削除しますか？<br>注意: この操作は元に戻せません。',
'confirm_rm_dump' => '本当にファイル「[dumpname]」を削除しますか？<br>注意: この操作は元に戻せません。',
'confirm_rm_event' => '本当にイベント「[name]」を削除しますか？<br>注意: この操作は元に戻せません。',
'confirm_rm_file' => '本当にドキュメント「[documentname]」のファイル「[name]」を削除しますか？<br>注意: この操作は元に戻せません。',
'confirm_rm_folder' => '本当にフォルダー「[foldername]」とその内容を削除しますか？<br>注意: この操作は元に戻せません。',
'confirm_rm_folder_files' => '本当にフォルダー「[foldername]」とそのサブフォルダー内のすべてのファイルを削除しますか？<br>注意: この操作は元に戻せません。',
'confirm_rm_group' => '本当にグループ「[groupname]」を削除しますか？<br>注意: この操作は元に戻せません。',
'confirm_rm_log' => '本当にログファイル「[logname]」を削除しますか？<br>注意: この操作は元に戻せません。',
'confirm_rm_task' => 'このタスクを削除することを確認してください。',
'confirm_rm_transmittal' => '送付文書を削除することを確認してください。',
'confirm_rm_transmittalitem' => '削除を確認',
'confirm_rm_user' => '本当にユーザー「[username]」を削除しますか？<br>注意: この操作は元に戻せません。',
'confirm_rm_user_from_processes' => '本当にユーザー「[username]」をすべてのプロセスから削除しますか？<br>注意: ユーザーが唯一または最後の承認者であった場合、ドキュメントが解放される可能性があります。',
'confirm_rm_version' => '本当にドキュメント「[documentname]」のバージョン [version] を削除しますか？<br>注意: この操作は元に戻せません。',
'confirm_transfer_link_document' => 'ドラッグしたドキュメントをリンクするか、その内容を対象ドキュメントの新しいバージョンとして転送するかを選択してください。正確に1バージョンしかないドキュメントのみ転送可能です。転送後、ドラッグしたドキュメントは削除されます。',
'confirm_transfer_objects' => '本当にユーザー「[username]」のドキュメント、フォルダーなどを移譲しますか？<br>注意: この操作は元に戻せません。',
'confirm_update_transmittalitem' => '更新を確認',
'content' => 'コンテンツ',
'continue' => '続行',
'converter_new_cmd' => 'コマンド',
'converter_new_mimetype' => '新しいMIMEタイプ',
'copied_to_checkout_as' => '[date] に [username] が「[filename]」としてチェックアウト領域にコピーしました',
'created' => '作成日時',
'createSubFolderForImportedFiles' => 'インポート用フォルダーを作成',
'createSubFolderForImportedFiles_desc' => '有効にすると、インポートされるフォルダーも作成されます。',
'create_download_link' => '',
'create_fulltext_index' => '全文索引を作成',
'create_fulltext_index_warning' => '全文索引を再作成しようとしています。これにはかなりの時間がかかり、システム全体のパフォーマンスが低下する可能性があります。本当に再作成する場合は操作を確認してください。',
'creation_date' => '作成日',
'cs_CZ' => 'チェコ語',
'current_filter' => '適用中のフィルター',
'current_password' => '現在のパスワード',
'current_quota' => '現在のシステム全体のクオータは [quota] に設定されています。',
'current_state' => '現在の状態',
'current_version' => '現在のバージョン',
'daily' => '毎日',
'dashboard' => 'ダッシュボード',
'databasesearch' => 'データベース',
'database_schema_version' => 'データベーススキーマのバージョン',
'data_loading' => 'データを読み込んでいます。しばらくお待ちください…',
'date' => '日付',
'days' => '日',
'debug' => 'デバッグ',
'december' => '12月',
'default_access' => 'デフォルトのアクセスモード',
'default_keywords' => '利用可能なキーワード',
'definitions' => '定義',
'delete' => '削除',
'details' => '詳細',
'details_version' => 'バージョンの詳細: [version]',
'de_DE' => 'ドイツ語',
'directory_check' => 'チェック',
'directory_check_cache_exists' => 'キャッシュ用ディレクトリが存在するか確認',
'directory_check_cache_writable' => 'キャッシュ用ディレクトリが書き込み可能か確認',
'directory_check_conf_writable' => '設定ディレクトリが書き込み可能か確認',
'directory_check_data_below_root' => 'データディレクトリが Web ディレクトリの下にないか確認',
'directory_check_data_exists' => 'データディレクトリが存在するか確認',
'directory_check_data_writable' => 'データディレクトリが書き込み可能か確認',
'directory_check_ext_below_docroot' => '拡張機能ディレクトリが Web ディレクトリの下にないか確認',
'directory_check_ext_exists' => '拡張機能ディレクトリが存在するか確認',
'directory_check_ext_writable' => '拡張機能ディレクトリが書き込み可能か確認',
'directory_check_index_exists' => '全文検索インデックス用ディレクトリが存在するか確認',
'directory_check_index_writable' => '全文検索インデックス用ディレクトリが書き込み可能か確認',
'directory_check_result' => '結果',
'disable_extension' => '拡張機能を無効化',
'disclaimer' => 'このエリアは機密区域です。許可された人員のみがアクセスできます。違反した場合は国内法および国際法に基づき処罰されます。',
'discspace' => 'ディスク容量',
'docs_in_reception_disabled' => '無効化されたユーザーによる受領中の文書',
'docs_in_reception_no_access' => '受領者がアクセスできない受領中の文書',
'docs_in_revision_disabled' => '無効化されたユーザーによる改訂中の文書',
'docs_in_revision_no_access' => 'レビュアーがアクセスできない改訂中の文書',
'docs_with_link_to_itself' => '自己リンクを持つ文書',
'docs_with_missing_revision_date' => '改訂日が設定されていない文書',
'document' => '文書',
'documentcontent' => '文書内容',
'documents' => '文書',
'documents_checked_out_by_you' => 'あなたがチェックアウトした文書',
'documents_expired' => '期限切れの文書',
'documents_in_process' => '処理中の文書',
'documents_locked' => 'ロックされた文書',
'documents_locked_by_you' => 'あなたがロックした文書',
'documents_only' => '文書のみ',
'documents_rejected' => '却下された文書',
'documents_to_approve' => 'あなたの承認待ちの文書',
'documents_to_correct' => '修正が必要な文書',
'documents_to_process' => '処理が必要な文書',
'documents_to_receipt' => '受領確認待ちの文書',
'documents_to_review' => 'あなたのレビュー待ちの文書',
'documents_to_revise' => 'あなたの改訂待ちの文書',
'documents_to_trigger_workflow' => 'ワークフロー中の文書',
'documents_user_draft' => '下書き',
'documents_user_expiration' => '期限切れの文書',
'documents_user_needs_correction' => '修正が必要な文書',
'documents_user_no_reception' => '受領されていない文書',
'documents_user_obsolete' => '廃止済みの文書',
'documents_user_reception' => '受領した文書',
'documents_user_rejected' => '却下された文書',
'documents_user_requiring_attention' => 'あなたが所有し、注意が必要な文書',
'documents_with_notification' => '通知が設定されている文書',
'document_access_permission_changed_email' => '権限が変更されました',
'document_access_permission_changed_email_body' => '権限が変更されました

文書: [name]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'document_access_permission_changed_email_body_html' => '<p>権限が変更されました</p>

<p>文書: [name]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'document_access_permission_changed_email_subject' => '[sitename]: [name] - 権限が変更されました',
'document_already_checkedout' => 'この文書はすでにチェックアウトされています',
'document_already_locked' => 'この文書はすでにロックされています',
'document_attribute_added_email_body' => '属性が追加されました

文書: [name]
属性: [attribute_name]
値: [attribute_value]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'document_attribute_added_email_body_html' => '<p>属性が追加されました</p>

<p>文書: [name]<br />
属性: [attribute_name]<br />
値: [attribute_value]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'document_attribute_added_email_subject' => '[sitename]: [name] - 属性が追加されました',
'document_attribute_changed_email_body' => '属性が変更されました

文書: [name]
属性: [attribute_name]
旧値: [attribute_old_value]
新値: [attribute_new_value]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'document_attribute_changed_email_body_html' => '<p>属性が変更されました</p>

<p>文書: [name]<br />
属性: [attribute_name]<br />
旧値: [attribute_old_value]<br />
新値: [attribute_new_value]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'document_attribute_changed_email_subject' => '[sitename]: [name] - 属性が変更されました',
'document_comment_changed_email' => 'コメントが変更されました',
'document_comment_changed_email_body' => 'コメントが変更されました

文書: [name]
旧コメント: [old_comment]
新コメント: [new_comment]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'document_comment_changed_email_body_html' => '<p>コメントが変更されました</p>

<p>文書: [name]<br />
旧コメント: [old_comment]<br />
新コメント: [new_comment]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'document_comment_changed_email_subject' => '[sitename]: [name] - コメントが変更されました',
'document_content_missing' => '文書の内容がありません',
'document_count' => '文書数',
'document_deleted' => '文書が削除されました',
'document_deleted_email' => '文書が削除されました',
'document_deleted_email_body' => '文書が削除されました

文書: [name]
親フォルダ: [folder_path]
ユーザー: [username]',
'document_deleted_email_body_html' => '<p>文書が削除されました</p>

<p>文書: [name]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]</p>',
'document_deleted_email_subject' => '[sitename]: [name] - 文書が削除されました',
'document_duplicate_name' => '重複する文書名',
'document_files' => '添付ファイル',
'document_has_no_workflow' => 'この文書にはワークフローが設定されていません',
'document_infos' => '文書情報',
'document_in_revision_no_date' => 'この文書は現在改訂中です。改訂が完了した後、新しい改訂日を設定できます。',
'document_is_checked_out' => 'この文書はチェックアウトされています',
'document_is_checked_out_remove' => 'この文書は現在チェックアウトされています。削除すると、チェックアウト中のバージョンは追加できなくなり、チェックアウト領域に残ります。',
'document_is_checked_out_update' => 'この文書は現在チェックアウトされています。新しいバージョンをアップロードすると、チェックアウト中のバージョンはチェックインできなくなります。',
'document_is_not_locked' => 'この文書はロックされていません',
'document_links' => '文書リンク',
'document_link_by' => 'リンク元',
'document_link_public' => '公開',
'document_moved_email' => '文書が移動されました',
'document_moved_email_body' => '文書が移動されました

文書: [name]
旧フォルダ: [old_folder_path]
新フォルダ: [new_folder_path]
ユーザー: [username]
URL: [url]',
'document_moved_email_body_html' => '<p>文書が移動されました</p>

<p>文書: [name]<br />
旧フォルダ: [old_folder_path]<br />
新フォルダ: [new_folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'document_moved_email_subject' => '[sitename]: [name] - 文書が移動されました',
'document_notify_added_email' => '通知リストに追加されました',
'document_notify_added_email_body' => '通知リストに追加されました。

文書名: [name]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'document_notify_added_email_body_html' => '<p>通知リストに追加されました。</p>
<p>文書名: [name]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'document_notify_added_email_subject' => '[sitename]: [name] - 通知リストに追加されました',
'document_notify_deleted_email' => '通知リストから削除されました',
'document_notify_deleted_email_body' => '通知リストから削除されました

文書名: [name]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'document_notify_deleted_email_body_html' => '<p>通知リストから削除されました</p>
<p>文書名: [name]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'document_notify_deleted_email_subject' => '[sitename]: [name] - 通知リストから削除されました',
'document_not_checkedout' => 'この文書はチェックアウトされていません',
'document_ownership_changed_email' => '所有者が変更されました',
'document_ownership_changed_email_body' => '所有者が変更されました

文書: [name]
親フォルダ: [folder_path]
旧所有者: [old_owner]
新所有者: [new_owner]
ユーザー: [username]
URL: [url]',
'document_ownership_changed_email_body_html' => '<p>所有者が変更されました</p>

<p>文書: [name]<br />
親フォルダ: [folder_path]<br />
旧所有者: [old_owner]<br />
新所有者: [new_owner]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'document_ownership_changed_email_subject' => '[sitename]: [name] - 所有者が変更されました',
'document_renamed_email' => '文書名が変更されました',
'document_renamed_email_body' => '文書名が変更されました

文書: [name]
親フォルダ: [folder_path]
旧名称: [old_name]
ユーザー: [username]
URL: [url]',
'document_renamed_email_body_html' => '<p>文書名が変更されました</p>

<p>文書: [name]<br />
親フォルダ: [folder_path]<br />
旧名称: [old_name]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'document_renamed_email_subject' => '[sitename]: [name] - 文書名が変更されました',
'document_status_changed_email' => '文書のステータスが変更されました',
'document_status_changed_email_body' => '文書のステータスが変更されました

文書: [name]
旧ステータス: [old_status]
新ステータス: [status]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'document_status_changed_email_body_html' => '<p>文書のステータスが変更されました</p>

<p>文書: [name]<br />
旧ステータス: [old_status]<br />
新ステータス: [status]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'document_status_changed_email_subject' => '[sitename]: [name] - 文書のステータスが変更されました',
'document_title' => '文書「[documentname]」',
'document_transfered_email_body' => '文書が他のユーザーに譲渡されました

文書: [name]
新所有者: [newuser]
旧所有者: [olduser]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'document_transfered_email_body_html' => '<p>文書が他のユーザーに譲渡されました</p>

<p>文書: [name]<br />
新所有者: [newuser]<br />
旧所有者: [olduser]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'document_transfered_email_subject' => '[sitename]: [name] - 文書が譲渡されました',
'document_updated_email' => '文書が更新されました',
'document_updated_email_body' => '文書が更新されました

文書: [name]
バージョン: [version]
親フォルダ: [folder_path]
ユーザー: [username]
コメント: [comment]
バージョンコメント: [version_comment]
URL: [url]',
'document_updated_email_body_html' => '<p>文書が更新されました</p>

<p>文書: [name]<br />
バージョン: [version]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
コメント: [comment]<br />
バージョンコメント: [version_comment]<br />
URL: [url]</p>',
'document_updated_email_subject' => '[sitename]: [name] - 文書が更新されました',
'document_versions' => '文書のバージョン',
'does_not_expire' => '有効期限なし',
'does_not_inherit_access_msg' => 'アクセス権を継承しない',
'download' => 'ダウンロード',
'download_extension' => '拡張機能を ZIP ファイルでダウンロード',
'download_header_approval_comment' => '承認コメント',
'download_header_approval_date' => '承認日',
'download_header_approval_state' => '承認ステータス',
'download_header_approver' => '承認者',
'download_header_document_name' => '文書名',
'download_header_document_no' => '文書番号',
'download_header_filename' => 'ファイル名',
'download_header_folder_name' => 'フォルダ名',
'download_header_folder_no' => 'フォルダ番号',
'download_header_internal_version' => '内部バージョン',
'download_header_reviewer' => 'レビュアー',
'download_header_review_comment' => 'レビューコメント',
'download_header_review_date' => 'レビュー日',
'download_header_review_state' => 'レビュー状態',
'download_header_state' => '状態',
'download_links' => 'ダウンロードリンク',
'download_link_email_body' => '',
'download_link_email_subject' => '',
'do_no_transfer_to_user' => 'プロセスをユーザーに譲渡しない',
'do_object_repair' => 'すべてのフォルダと文書を修復',
'do_object_setchecksum' => 'チェックサムを設定',
'do_object_setfilesize' => 'ファイルサイズを設定',
'do_object_setfiletype' => 'ファイルタイプを設定',
'do_object_unlink' => '文書バージョンを削除',
'draft' => '下書き',
'draft_pending_approval' => '承認待ち',
'draft_pending_review' => 'レビュー待ち',
'drag_icon_here' => 'ここにフォルダまたは文書をドラッグしてください！',
'dropfolderdir_missing' => 'サーバー上にあなたの個人用ドロップフォルダが存在しません！管理者に作成を依頼してください。',
'dropfolder_file' => 'ドロップフォルダからのファイル',
'dropfolder_folder' => 'ドロップフォルダからのフォルダ',
'dropfolder_metadata' => 'インポート対象ファイルのメタデータ',
'dropupload' => '高速アップロード',
'drop_files_here' => 'ここにファイルをドロップしてください！',
'drop_files_here_or_click' => 'ここにファイルをドロップ、またはクリックしてアップロード！',
'dump_creation' => 'データベースダンプ作成',
'dump_creation_warning' => 'この操作でデータベース内容のダンプファイルを作成できます。作成後、ダンプファイルはサーバーのデータフォルダに保存されます。',
'dump_list' => '既存のダンプファイル',
'dump_remove' => 'ダンプファイルを削除',
'duplicates' => '重複',
'duplicate_content' => '重複コンテンツ',
'duplicate_sequences' => 'フォルダ内の重複した連番',
'edit' => '編集',
'edit_attributes' => '属性を編集',
'edit_comment' => 'コメントを編集',
'edit_default_keywords' => 'キーワードを編集',
'edit_document_access' => 'アクセス権',
'edit_document_notify' => 'ドキュメント通知リスト',
'edit_document_props' => 'ドキュメントを編集',
'edit_event' => 'イベントを編集',
'edit_existing_access' => 'アクセスリストを編集',
'edit_existing_attribute_groups' => '属性グループを編集',
'edit_existing_notify' => '通知リストを編集',
'edit_folder_access' => 'アクセス権',
'edit_folder_attrdefgrp' => '属性グループを編集',
'edit_folder_notify' => 'フォルダ通知リスト',
'edit_folder_props' => 'フォルダを編集',
'edit_group' => 'グループを編集',
'edit_online' => 'オンライン編集',
'edit_online_not_allowed' => '最新バージョンを作成していないため、このファイルを編集することはできません。新しいバージョンをアップロードしてください。',
'edit_online_warning' => '変更を保存すると、新しいバージョンを作成せずに現在のバージョンの内容が上書きされます。',
'edit_task' => 'タスクを編集',
'edit_transmittal_props' => '伝達プロパティを編集',
'edit_user' => 'ユーザーを編集',
'edit_user_details' => 'ユーザー詳細を編集',
'edit_version' => 'バージョンを編集',
'el_GR' => 'ギリシャ語',
'email' => 'メール',
'email_error_title' => 'メールが入力されていません',
'email_footer' => 'メール設定は「マイアカウント」から変更できます',
'email_footer_html' => '<p>メール設定は「マイアカウント」から変更できます</p>',
'email_header' => 'これは DMS サーバからの自動送信メッセージです。',
'email_header_html' => '<p>これは DMS サーバからの自動送信メッセージです。</p>',
'email_not_given' => '有効なメールアドレスを入力してください。',
'empty_attribute_group_list' => '属性グループがありません',
'empty_folder_list' => 'ドキュメントまたはフォルダがありません',
'empty_list' => '項目がありません',
'empty_notify_list' => '項目がありません',
'enable_extension' => '拡張機能を有効化',
'enddate' => '終了日',
'ja_JP' => '日本語',
'equal_transition_states' => '開始状態と終了状態が同じです',
'error' => 'エラー',
'error_add_aro' => 'アクセス要求オブジェクトの追加中にエラーが発生しました',
'error_add_permission' => '権限追加中にエラーが発生しました',
'error_cleared_cache' => 'キャッシュクリア中にエラーが発生しました',
'error_document_indexed' => 'ドキュメントのインデックス作成中にエラーが発生しました',
'error_edit_task' => 'タスク保存中にエラーが発生しました',
'error_extension_getlist' => 'リポジトリから拡張機能リスト取得中にエラーが発生しました',
'error_importfs' => 'ファイルシステムからのインポート中にエラーが発生しました',
'error_no_document_selected' => 'ドキュメントが選択されていません',
'error_no_folder_selected' => 'フォルダが選択されていません',
'error_occured' => 'エラーが発生しました',
'error_remove_document' => 'ドキュメント削除中にエラーが発生しました',
'error_remove_folder' => 'フォルダ削除中にエラーが発生しました',
'error_remove_permission' => '権限削除中にエラーが発生しました',
'error_rm_user_processes' => 'ユーザーを全プロセスから削除中にエラーが発生しました',
'error_rm_user_processes_no_docs' => 'ドキュメントが選択されていません',
'error_rm_workflow' => 'ワークフロー削除中にエラーが発生しました',
'error_rm_workflow_action' => 'ワークフローアクション削除中にエラーが発生しました',
'error_rm_workflow_state' => 'ワークフロー状態削除中にエラーが発生しました',
'error_toogle_permission' => '権限変更中にエラーが発生しました',
'error_transfer_document' => 'ドキュメント転送中にエラーが発生しました',
'error_trigger_workflow' => 'ワークフローの遷移実行中にエラーが発生しました',
'error_update_document' => 'ドキュメント更新中にエラーが発生しました',
'error_uploading_reviewer_only' => 'ドキュメント作成中にエラーが発生しました。レビュアーはいますが、承認者がいません。',
'es_ES' => 'スペイン語',
'event' => 'イベント',
'event_details' => 'イベント詳細',
'exclude_items' => '項目を除外',
'expired' => '期限切れ',
'expired_at_date' => '[datetime]に期限切れ',
'expired_docs_mail_subject' => '期限切れドキュメント',
'expired_documents' => '期限切れドキュメント',
'expires' => '有効期限',
'expire_by_date' => '期限日まで有効',
'expire_in_1d' => '1日で期限切れ',
'expire_in_1h' => '1時間で期限切れ',
'expire_in_1m' => '1か月で期限切れ',
'expire_in_1w' => '1週間で期限切れ',
'expire_in_1y' => '1年で期限切れ',
'expire_in_24h' => '24時間で期限切れ',
'expire_in_2h' => '2時間で期限切れ',
'expire_in_2y' => '2年で期限切れ',
'expire_in_3y' => '3年で期限切れ',
'expire_today' => '本日期限切れ',
'expire_tomorrow' => '明日期限切れ',
'expiry_changed_email' => '有効期限が変更されました',
'expiry_changed_email_body' => '有効期限が変更されました

ドキュメント: [name]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'expiry_changed_email_body_html' => '<p>有効期限が変更されました</p>

<p>ドキュメント: [name]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'expiry_changed_email_subject' => '[sitename]: [name] - 有効期限変更',
'export' => 'エクスポート',
'export_user_list_csv' => 'ユーザーをCSVでエクスポート',
'extension_archive' => '拡張機能',
'extension_changelog' => '変更履歴',
'extension_config' => '設定',
'extension_info' => '拡張機能',
'extension_is_off_now' => '拡張機能は現在無効',
'extension_is_on_now' => '拡張機能は現在有効',
'extension_loading' => '拡張機能を読み込み中...',
'extension_manager' => '拡張機能管理',
'extension_mgr_error_upload' => '拡張機能アップロード中にエラーが発生しました。',
'extension_mgr_installed' => 'インストール済み',
'extension_mgr_no_toggle' => '設定ファイルが書き込み不可のため、拡張機能を有効/無効にできません。',
'extension_mgr_no_upload' => '拡張機能ディレクトリが書き込み不可のため、新しい拡張機能をアップロードできません。',
'extension_mgr_no_zipfile' => 'アップロードされたファイルはzipではありません',
'extension_mgr_repository' => '利用可能',
'extension_mgr_upload_disabled' => '設定により、新しい拡張機能のアップロードはできません。',
'extension_missing_name' => '拡張機能名が指定されていません',
'extension_readme' => 'README',
'extension_toggle_error' => '拡張機能の切替に失敗しました',
'extension_version_list' => 'バージョン',
'facetfullsearch' => '全文検索（ファセット）',
'february' => '2月',
'file' => 'ファイル',
'files' => 'ファイル',
'filesize' => 'ファイルサイズ',
'files_deletion' => 'ファイル削除',
'files_deletion_warning' => 'このオプションを使用すると、DMS フォルダ内の全てのファイルを削除できます。バージョン情報は残ります。',
'files_loading' => 'ファイルリストの読み込み中です…',
'filetype' => 'ファイルタイプ',
'filter_for_documents' => 'ドキュメント用の追加フィルター',
'filter_for_documents_and_folders' => 'フォルダおよびドキュメント用の追加フィルター',
'filter_for_folders' => 'フォルダ用の追加フィルター',
'finished_workflow_log' => '完了したワークフロー',
'folder' => 'フォルダ',
'folders' => 'フォルダ',
'folders_and_documents_statistic' => 'コンテンツ概要',
'folders_with_notification' => '通知付きフォルダ',
'folder_access_permission_changed_email_body' => '権限が変更されました

フォルダ: [name]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'folder_access_permission_changed_email_body_html' => '<p>権限が変更されました</p>

<p>フォルダ: [name]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'folder_access_permission_changed_email_subject' => '[sitename]: [name] - 権限変更',
'folder_attribute_added_email_body' => '属性が追加されました

フォルダ: [name]
属性: [attribute_name]
値: [attribute_value]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'folder_attribute_added_email_body_html' => '<p>属性が追加されました</p>

<p>フォルダ: [name]<br />
属性: [attribute_name]<br />
値: [attribute_value]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'folder_attribute_added_email_subject' => '[sitename]: [name] - 属性追加',
'folder_attribute_changed_email_body' => '属性が変更されました

フォルダ: [name]
属性: [attribute_name]
古い値: [attribute_old_value]
新しい値: [attribute_new_value]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'folder_attribute_changed_email_body_html' => '<p>属性が変更されました</p>

<p>フォルダ: [name]<br />
属性: [attribute_name]<br />
古い値: [attribute_old_value]<br />
新しい値: [attribute_new_value]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'folder_attribute_changed_email_subject' => '[sitename]: [name] - 属性変更',
'folder_comment_changed_email' => 'コメントが変更されました',
'folder_comment_changed_email_body' => 'コメントが変更されました

フォルダ: [name]
古いコメント: [old_comment]
新しいコメント: [new_comment]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'folder_comment_changed_email_body_html' => '<p>コメントが変更されました</p>

<p>フォルダ: [name]<br />
古いコメント: [old_comment]<br />
新しいコメント: [new_comment]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'folder_comment_changed_email_subject' => '[sitename]: [name] - コメント変更',
'folder_contents' => 'フォルダ内容',
'folder_deleted_email' => 'フォルダが削除されました',
'folder_deleted_email_body' => 'フォルダが削除されました

フォルダ: [name]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'folder_deleted_email_body_html' => '<p>フォルダが削除されました</p>

<p>フォルダ: [name]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'folder_deleted_email_subject' => '[sitename]: [name] - フォルダ削除',
'folder_infos' => 'フォルダ情報',
'folder_moved_email' => 'フォルダが移動されました',
'folder_moved_email_body' => 'フォルダ移動

フォルダ: [name]
旧フォルダ: [old_folder_path]
新フォルダ: [new_folder_path]
ユーザー: [username]
URL: [url]',
'folder_moved_email_body_html' => '<p>フォルダ移動</p>

<p>フォルダ: [name]<br />
旧フォルダ: [old_folder_path]<br />
新フォルダ: [new_folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'folder_moved_email_subject' => '[sitename]: [name] - フォルダ移動',
'folder_notify_added_email' => '通知リストに追加されました',
'folder_notify_added_email_body' => '通知リストに追加されました

フォルダ: [name]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'folder_notify_added_email_body_html' => '<p>通知リストに追加されました</p>
<p>フォルダ: [name]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'folder_notify_added_email_subject' => '[sitename]: [name] - 通知リストに追加',
'folder_notify_deleted_email_body' => '通知リストから削除されました

フォルダ: [name]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'folder_notify_deleted_email_body_html' => '<p>通知リストから削除されました</p>
<p>フォルダ: [name]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'folder_notify_deleted_email_subject' => '[sitename]: [name] - 通知リストから削除',
'folder_ownership_changed_email_body' => '所有者が変更されました

フォルダ: [name]
親フォルダ: [folder_path]
旧所有者: [old_owner]
新所有者: [new_owner]
ユーザー: [username]
URL: [url]',
'folder_ownership_changed_email_body_html' => '<p>所有者が変更されました</p>

<p>フォルダ: [name]<br />
親フォルダ: [folder_path]<br />
旧所有者: [old_owner]<br />
新所有者: [new_owner]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'folder_ownership_changed_email_subject' => '[sitename]: [name] - 所有者変更',
'folder_renamed_email' => 'フォルダ名変更',
'folder_renamed_email_body' => 'フォルダ名が変更されました

フォルダ: [name]
親フォルダ: [folder_path]
旧名: [old_name]
ユーザー: [username]
URL: [url]',
'folder_renamed_email_body_html' => '<p>フォルダ名が変更されました</p>

<p>フォルダ: [name]<br />
親フォルダ: [folder_path]<br />
旧名: [old_name]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'folder_renamed_email_subject' => '[sitename]: [name] - フォルダ名変更',
'folder_title' => 'フォルダ \'[foldername]\'',
'foot_note' => '脚注',
'force_update' => '更新',
'friday' => '金曜日',
'friday_abbr' => '金',
'from' => '送信元',
'fr_FR' => 'フランス語',
'fullsearch' => '全文検索',
'fullsearch_hint' => '全文検索インデックスを使用',
'fulltextsearch_disabled' => '全文検索インデックスは無効です',
'fulltext_converters' => 'ドキュメント変換のインデックス作成',
'fulltext_info' => '全文検索インデックス情報',
'func_proc_open_missing' => 'ドキュメント内容のインデックス作成には proc_open が必要です。この関数がない場合、メタデータのみがインデックスされます。',
'global_attributedefinitiongroups' => '属性グループ',
'global_attributedefinitions' => '属性',
'global_default_keywords' => 'グローバルキーワード',
'global_document_categories' => 'カテゴリ',
'global_link_types' => 'リンクタイプ',
'global_workflows' => 'ワークフロー',
'global_workflow_actions' => 'ワークフローアクション',
'global_workflow_states' => 'ワークフローステート',
'group' => 'グループ',
'groups' => 'グループ',
'group_approval_summary' => 'グループ承認サマリー',
'group_exists' => 'グループは既に存在します。',
'group_info' => 'グループ情報',
'group_is_mandatory_approver' => 'このグループは必須承認者です',
'group_is_mandatory_reviewer' => 'このグループは必須レビュアーです',
'group_management' => 'グループ管理',
'group_members' => 'グループメンバー',
'group_previously_removed_from_approvers' => 'グループは以前に承認者から削除されました。',
'group_previously_removed_from_recipients' => 'グループは以前に受信者から削除されました。',
'group_previously_removed_from_reviewers' => 'グループは以前にレビュアーから削除されました。',
'group_previously_removed_from_revisors' => 'グループは以前にレビュアーから削除されました。',
'group_receipt_summary' => 'グループ受領サマリー',
'group_review_removed' => 'ステータス変更: グループ [name] のレビューが削除されました。',
'group_review_summary' => 'グループレビューサマリー',
'group_revision_summary' => 'グループ改訂サマリー',
'guest_login' => 'ゲストとしてログイン',
'guest_login_disabled' => 'ゲストログインは無効です。',
'hash' => 'ハッシュ',
'help' => 'ヘルプ',
'home_folder' => 'ホームフォルダ',
'hook_name' => 'フック名',
'hourly' => '毎時',
'hours' => '時間',
'hr_HR' => 'クロアチア語',
'human_readable' => '人間に読みやすい形式のアーカイブ',
'hu_HU' => 'ハンガリー語',
'id' => 'ID',
'identical_version' => '新しいバージョンは現在のバージョンと同じです。',
'id_ID' => 'インドネシア語',
'import' => 'インポート',
'importfs' => 'ファイルシステムからインポート',
'import_extension' => 'インポート拡張',
'import_fs' => 'ファイルシステムからインポート',
'import_fs_warning' => 'これはドロップフォルダ内のフォルダでのみ動作します。操作はすべてのフォルダとファイルを再帰的にインポートします。ファイルは即時リリースされます。',
'import_users' => 'ユーザーをインポート',
'import_users_addnew' => '新規ユーザーを追加',
'import_users_no_column_mapping' => 'ユーザーリストをアップロードしてください',
'import_users_update' => '既存ユーザーを更新',
'include_content' => '内容を含める',
'include_documents' => 'ドキュメントを含める',
'include_subdirectories' => 'サブディレクトリを含める',
'indexing_tasks_in_queue' => 'インデックス作業待機中',
'index_converters' => 'インデックス変換',
'index_document_added' => 'ドキュメントを追加',
'index_document_unchanged' => 'ドキュメントに変更なし',
'index_document_updated' => 'ドキュメントを更新',
'index_done' => '完了',
'index_error' => 'エラー',
'index_folder' => 'フォルダをインデックス',
'index_folder_added' => 'フォルダを追加',
'index_folder_unchanged' => 'フォルダに変更なし',
'index_folder_updated' => 'フォルダを更新',
'index_no_content' => '内容はインデックスされませんでした',
'index_pending' => '保留中',
'index_processing' => '処理中 …',
'index_waiting' => '待機中',
'individuals' => '個人',
'individuals_in_groups' => 'グループメンバー',
'ind_review_removed' => 'ステータス変更: ユーザー [name] のレビューが削除されました。',
'info_recipients_tab_not_released' => 'このドキュメントバージョンはリリースされていないため、受領確認できません。',
'info_rm_user_from_processes_none' => 'このユーザーは現在タスクを持っていません。',
'info_rm_user_from_processes_user' => '処理中でないタスクのみ別ユーザーに移行できます。既に処理済みのタスクは、ユーザー削除の履歴として記録されます。',
'inherited' => '継承',
'inherits_access_copy_msg' => '継承されたアクセスリストをコピー',
'inherits_access_empty_msg' => '空のアクセスリストから開始',
'inherits_access_msg' => 'アクセスは継承されています。',
'insecure_installation' => 'SeedDMS のインストールは重大な脆弱性があります。設定やアップロードファイルがウェブサーバーから読み取れる可能性があります。doc/README.Install.md の「セキュリティ上の注意」を参照してください。',
'installed_apache_extensions' => 'インストール済み Apache 拡張',
'installed_php_extensions' => 'インストール済み PHP 拡張',
'internal_error' => '内部エラー',
'internal_error_exit' => '内部エラー。リクエストを完了できません。',
'invalid_access_mode' => '無効なアクセスモード',
'invalid_action' => '無効な操作',
'invalid_approval_status' => '無効な承認ステータス',
'invalid_create_date_end' => '作成日範囲の終了日が無効です。',
'invalid_create_date_start' => '作成日範囲の開始日が無効です。',
'invalid_doc_id' => '無効なドキュメントID',
'invalid_dropfolder_folder' => 'ドロップフォルダ内の無効なフォルダ',
'invalid_expiration_date' => '無効な有効期限',
'invalid_expiration_date_end' => '有効期限範囲の終了日が無効です。',
'invalid_expiration_date_start' => '有効期限範囲の開始日が無効です。',
'invalid_file_id' => '無効なファイルID',
'invalid_folder_id' => '無効なフォルダID',
'invalid_group_id' => '無効なグループID',
'invalid_link_id' => '無効なリンクID',
'invalid_request_token' => '無効なリクエストトークン',
'invalid_review_status' => '無効なレビュー状態',
'invalid_sequence' => '無効なシーケンス値',
'invalid_status' => '無効なドキュメントステータス',
'invalid_target_doc_id' => '無効なターゲットドキュメントID',
'invalid_target_folder' => '無効なターゲットフォルダID',
'invalid_user_id' => '無効なユーザーID',
'invalid_version' => '無効なドキュメントバージョン',
'in_folder' => 'フォルダ内',
'in_revision' => '改訂中',
'in_workflow' => 'ワークフロー中',
'iptc_metadata' => 'IPTC データ',
'is_disabled' => 'アカウントを無効化',
'is_hidden' => 'ユーザーリストから非表示',
'it_IT' => 'イタリア語',
'january' => '1月',
'js_confirm_cancel_checkout' => '確認のためチェックしてください',
'js_form_error' => 'フォームに # 件のエラーがあります。',
'js_form_errors' => 'フォームに # 件のエラーがあります。',
'js_invalid_email' => '無効なメールアドレスです',
'js_no_approval_group' => '承認グループを選択してください',
'js_no_approval_status' => '承認ステータスを選択してください',
'js_no_comment' => 'コメントがありません',
'js_no_currentpwd' => '現在のパスワードを入力してください',
'js_no_document' => 'ドキュメントを選択してください',
'js_no_email' => 'メールアドレスを入力してください',
'js_no_file' => 'ファイルを選択してください',
'js_no_folder' => 'フォルダを選択してください',
'js_no_keywords' => 'キーワードを指定してください',
'js_no_login' => 'ユーザー名を入力してください',
'js_no_name' => '名前を入力してください',
'js_no_override_status' => '新しいステータスを選択してください',
'js_no_pwd' => 'パスワードを入力してください',
'js_no_query' => 'クエリを入力してください',
'js_no_review_group' => 'レビューグループを選択してください',
'js_no_review_status' => 'レビュー状態を選択してください',
'js_pwd_not_conf' => 'パスワードと確認が一致しません',
'js_select_user' => 'ユーザーを選択してください',
'js_select_user_or_group' => '少なくともユーザーまたはグループを選択してください',
'js_unequal_passwords' => 'パスワードが一致しません',
'july' => '7月',
'june' => '6月',
'keep' => '変更しない',
'keep_doc_status' => 'ドキュメントステータスを保持',
'keywords' => 'キーワード',
'keywords_loading' => 'キーワードリストを読み込み中…',
'keyword_exists' => 'キーワードは既に存在します',
'ko_KR' => '韓国語',
'language' => '言語',
'lastaccess' => '最終アクセス',
'last_update' => '最終更新',
'latest_newdocuments' => '最近追加されたドキュメント',
'latest_statuschange' => '最近ステータスが変更されたドキュメント',
'latest_updateddocuments' => '最近更新されたドキュメント',
'legend' => '凡例',
'librarydoc' => 'ライブラリからのドキュメント',
'linked_document' => 'リンクされたドキュメント',
'linked_documents' => '関連ドキュメント',
'linked_files' => '添付ファイル',
'linked_to_current_version' => '現在のバージョンにリンク済み',
'linked_to_document' => 'ドキュメントにリンク済み',
'linked_to_this_version' => 'このバージョンにリンク済み',
'link_alt_updatedocument' => '現在の最大アップロードサイズより大きいファイルをアップロードする場合は、代替の <a href="%s">アップロードページ</a> を使用してください。',
'link_document' => 'ドキュメントをリンク',
'link_to' => 'リンク先',
'link_to_version' => 'バージョンに添付',
'list_access_rights' => 'すべてのアクセス権を表示 …',
'list_contains_no_access_docs' => 'リストにはアクセス権のないドキュメントが含まれており表示されません。',
'list_conversion_overview' => '既存の MIME タイプと変換サービス',
'list_conversion_services' => '変換サービス一覧',
'list_hooks' => 'フック一覧',
'list_notification_services' => '通知サービス一覧',
'list_of_recipients_has_disabled_users' => '受信者リストに無効なユーザーが含まれています。',
'list_tasks' => 'タスク一覧',
'local_file' => 'ローカルファイル',
'locked_by' => 'ロック中',
'lock_document' => 'ロック',
'lock_message' => 'このドキュメントは [username] によってロックされています。権限のあるユーザーのみロック解除できます。',
'lock_status' => 'ステータス',
'logfile' => 'ログファイル',
'logfile_loading' => 'ログファイルを読み込み中…',
'login' => 'ログイン',
'login_disabled_text' => 'アカウントは無効化されています。ログイン失敗回数が多いためです。',
'login_disabled_title' => 'アカウント無効',
'login_error_text' => 'サインインエラー。ユーザーIDまたはパスワードが正しくありません。',
'login_error_title' => 'サインインエラー',
'login_not_given' => 'ユーザー名が入力されていません',
'login_ok' => 'サインイン成功',
'login_restrictions_apply' => '制限によりログイン失敗',
'logout' => 'ログアウト',
'log_management' => 'ログ管理',
'lo_LA' => 'ラオ語',
'malformed_expiration_date' => '不正な有効期限形式',
'manager' => 'マネージャー',
'manager_of_group' => 'あなたはこのグループのマネージャーです',
'mandatory_approvergroups' => '必須承認グループ',
'mandatory_approvergroup_no_access' => '必須承認グループ \'[group]\' に十分なアクセス権がありません。',
'mandatory_approvers' => '必須承認者',
'mandatory_approver_no_access' => '必須承認者 \'[user]\' に十分なアクセス権がないか、承認者として許可されていません。',
'mandatory_reviewergroups' => '必須レビュアーグループ',
'mandatory_reviewergroup_no_access' => '必須レビュアーグループ \'[group]\' に十分なアクセス権がありません。',
'mandatory_reviewers' => '必須レビュアー',
'mandatory_reviewer_no_access' => '必須レビュアー \'[user]\' に十分なアクセス権がないか、レビュアーとして許可されていません。',
'march' => '3月',
'mark_document' => 'バッチ操作用にドキュメントをマーク',
'mark_folder' => 'バッチ操作用にフォルダをマーク',
'max_upload_size' => '最大アップロードサイズ',
'may' => '5月',
'menu_dropfolder' => 'ドロップフォルダ',
'menu_upload_from_dropfolder' => 'このファイルをインポート',
'message' => 'メッセージ',
'mimetype' => 'MIMEタイプ',
'minutes' => '分',
'misc' => 'その他',
'missing_checksum' => 'チェックサムがありません',
'missing_file' => 'ファイルがありません',
'missing_filesize' => 'ファイルサイズがありません',
'missing_func_class_note' => '注意',
'missing_php_class' => 'PHP クラス [classname] が見つかりません',
'missing_php_extension' => 'PHP 拡張 [extname] が見つかりません',
'missing_php_extensions' => '欠損している PHP 拡張を確認',
'missing_php_function' => 'PHP 関数 [funcname] が見つかりません',
'missing_php_functions_and_classes' => '欠損している PHP 関数とクラスを確認',
'missing_reception' => '受領情報がありません',
'missing_request_object' => 'リクエストオブジェクトがありません',
'missing_transition_user_group' => '遷移用のユーザー/グループがありません',
'modification_date' => '変更日',
'modified' => '変更済み',
'monday' => '月曜日',
'monday_abbr' => '月',
'monthly' => '毎月',
'month_view' => '月表示',
'more_objects_loading' => 'さらに読み込み中 …',
'move' => '移動',
'move_clipboard' => 'クリップボードに移動',
'move_document' => 'ドキュメントを移動',
'move_folder' => 'フォルダを移動',
'move_into_rootfolder' => 'ルートフォルダに移動',
'must_drop_one_file' => '1つのファイルのみドロップできます',
'my_account' => 'マイアカウント',
'my_documents' => 'マイドキュメント',
'my_transmittals' => '自分の送付書',
'name' => '名前',
'nav_brand_admin_tools' => '管理ツール',
'nav_brand_calendar' => 'カレンダー',
'nav_brand_my_account' => 'マイアカウント',
'nav_brand_my_documents' => 'マイドキュメント',
'nav_brand_view_document' => 'ドキュメント',
'nav_brand_view_folder' => 'フォルダ',
'nb_NO' => 'ノルウェー語（ブークモール）',
'needs_correction' => '修正が必要',
'needs_workflow_action' => 'このドキュメントはあなたの対応が必要です。ワークフロータブを確認してください。',
'network_drive' => 'ネットワークドライブ',
'never' => 'なし',
'new' => '新規',
'new_attrdef' => '属性定義を追加',
'new_default_keywords' => 'キーワードを追加',
'new_default_keyword_category' => 'カテゴリを追加',
'new_documents' => '新規ドキュメント',
'new_documents_today' => '本日の新規ドキュメント',
'new_documents_yesterday' => '昨日の新規ドキュメント',
'new_document_category' => 'カテゴリを追加',
'new_document_email' => '新規ドキュメント',
'new_document_email_body' => '新規ドキュメント

名前: [name]
親フォルダ: [folder_path]
コメント: [comment]
バージョンコメント: [version_comment]
ユーザー: [username]
URL: [url]',
'new_document_email_body_html' => '<p>新規ドキュメント</p>

<p>名前: [name]<br />
親フォルダ: [folder_path]<br />
コメント: [comment]<br />
バージョンコメント: [version_comment]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'new_document_email_subject' => '[sitename]: [folder_name] - 新規ドキュメント',
'new_file_email' => '新規添付ファイル',
'new_file_email_body' => '新規添付ファイル

名前: [name]
ドキュメント: [document]
コメント: [comment]
ユーザー: [username]
URL: [url]',
'new_file_email_body_html' => '<p>新規添付ファイル</p>

<p>名前: [name]<br />
ドキュメント: [document]<br />
コメント: [comment]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'new_file_email_subject' => '[sitename]: [document] - 新規添付ファイル',
'new_folder' => '新規フォルダ',
'new_link_type' => 'リンクタイプを追加',
'new_password' => '新しいパスワード',
'new_subfolder_email' => '新規フォルダ',
'new_subfolder_email_body' => '新規フォルダ

名前: [name]
親フォルダ: [folder_path]
コメント: [comment]
ユーザー: [username]
URL: [url]',
'new_subfolder_email_body_html' => '<p>新規フォルダ</p>

<p>名前: [name]<br />
親フォルダ: [folder_path]<br />
コメント: [comment]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'new_subfolder_email_subject' => '[sitename]: [name] - 新規フォルダ',
'new_user_image' => '新規画像',
'next_revision_abbr' => '次の改訂',
'next_state' => '新しいステータス',
'nl_NL' => 'オランダ語',
'no' => 'いいえ',
'notification' => '通知',
'notification_msg_tmpl' => 'テンプレート',
'notification_recvtype' => '受信者タイプ',
'notification_recv_any' => '任意',
'notification_recv_approver' => '承認者',
'notification_recv_notification' => '通知者',
'notification_recv_owner' => '所有者',
'notification_recv_reviewer' => 'レビュアー',
'notification_recv_uploader' => 'アップローダー',
'notification_recv_workflow' => 'ワークフロー',
'notification_service_no_filter' => 'この通知サービスにはフィルターがありません。',
'notification_tmpl' => 'テンプレート',
'not_subscribed' => '未登録',
'november' => '11月',
'now' => '現在',
'no_action' => 'アクション不要',
'no_approval_needed' => '承認待ちはありません。',
'no_attached_files' => '添付ファイルなし',
'no_attributes_defined' => 'カスタム属性が作成されていません。',
'no_attribute_definitions' => '属性定義はありません',
'no_backup_dir' => 'バックアップディレクトリが設定されていません。',
'no_current_version' => '古いバージョンの SeedDMS を使用しています。最新バージョンは [latestversion] です。',
'no_default_keywords' => 'キーワードはありません',
'no_docs_checked_out' => 'チェックアウト中のドキュメントはありません',
'no_docs_draft' => 'ドラフトのドキュメントはありません',
'no_docs_expired' => '期限切れのドキュメントはありません',
'no_docs_locked' => 'ロック中のドキュメントはありません。',
'no_docs_needs_correction' => '修正が必要なドキュメントはありません',
'no_docs_obsolete' => '廃止予定のドキュメントはありません',
'no_docs_rejected' => '却下されたドキュメントはありません。',
'no_docs_to_approve' => '承認が必要なドキュメントはありません。',
'no_docs_to_look_at' => '対応が必要なドキュメントはありません。',
'no_docs_to_receipt' => '受領確認が必要なドキュメントはありません',
'no_docs_to_review' => 'レビューが必要なドキュメントはありません。',
'no_docs_to_revise' => '改訂が必要なドキュメントはありません。',
'no_email_or_login' => 'ログインとメールを入力してください',
'no_fulltextindex' => '全文検索インデックスはありません',
'no_groups' => 'グループはありません',
'no_group_members' => 'このグループにはメンバーがいません',
'no_linked_files' => 'リンクされたファイルはありません',
'no_mimetype' => 'MIMEタイプがありません',
'no_previous_versions' => '他のバージョンはありません',
'no_receipt_needed' => '受領確認が必要なドキュメントはありません。',
'no_review_needed' => 'レビュー待ちはありません。',
'no_revision_date' => '改訂日がありません',
'no_revision_needed' => '改訂待ちはありません。',
'no_revision_planed' => '改訂予定のドキュメントはありません',
'no_update_cause_locked' => 'このドキュメントは更新できません。ロックユーザーに連絡してください。',
'no_user_image' => '画像はありません',
'no_value_set' => '値が設定されていません',
'no_version_check' => 'SeedDMS の新しいバージョンの確認に失敗しました。PHP 設定で allow_url_fopen が 0 に設定されている可能性があります。',
'no_version_modification' => 'バージョンに変更なし',
'no_workflows' => 'ワークフローは作成されていません',
'no_workflow_available' => '利用可能なワークフローはありません',
'number_count' => '番号',
'n_of_m_approved' => '[approved]/[total] 承認済み',
'n_of_m_reviewed' => '[reviewed]/[total] レビュー済み',
'n_of_m_revised' => '[revised]/[total] 改訂済み',
'objectcheck' => 'フォルダ/ドキュメントのチェック',
'objects_without_attribute' => 'この属性のないオブジェクト',
'object_check_critical' => '重大なエラー',
'object_check_warning' => '警告',
'objtype_unknown' => '不明',
'obsolete' => '廃止',
'october' => '10月',
'old' => '古い',
'only_jpg_user_images' => 'ユーザー画像には .jpg のみ使用可能',
'operation_disallowed' => '操作は許可されていません',
'orderby' => '並び替え',
'orderby_date_asc' => '日付順（昇順）',
'orderby_date_desc' => '日付順（降順）',
'orderby_id_asc' => 'ID順（昇順）',
'orderby_id_desc' => 'ID順（降順）',
'orderby_name_asc' => '名前順（昇順）',
'orderby_name_desc' => '名前順（降順）',
'orderby_relevance' => '関連性順',
'orderby_unsorted' => '未ソート',
'order_by_sequence_off' => '設定でシーケンスによる並び替えは無効です。有効にするには設定を変更してください。',
'original_filename' => '元のファイル名',
'overall_indexing_progress' => '全体のインデックス進行状況',
'owner' => '所有者',
'parent_folder' => '親フォルダ',
'password' => 'パスワード',
'password_already_used' => '既に使用されているパスワードです',
'password_expiration' => 'パスワードの有効期限',
'password_expiration_text' => 'パスワードの有効期限が切れています。新しいパスワードを設定してください。',
'password_expired' => 'パスワードが期限切れです',
'password_expires_in_days' => 'パスワードはあと %s 日で期限切れです。',
'password_forgotten' => 'パスワードを忘れた場合',
'password_forgotten_email_body' => 'SeedDMSのユーザー様、

パスワード変更のリクエストを受け付けました。

以下のリンクをクリックしてパスワードを変更してください：

[url_prefix]out/out.ChangePassword.php?hash=[hash]

ログインできない場合は、管理者にお問い合わせください。',
'password_forgotten_email_body_html' => '<p>SeedDMSのユーザー様、</p>

<p>パスワード変更のリクエストを受け付けました。</p>

<p>以下のリンクをクリックしてパスワードを変更してください：</p>

<p>[url_prefix]out/out.ChangePassword.php?hash=[hash]</p>

<p>ログインできない場合は、管理者にお問い合わせください。</p>',
'password_forgotten_email_subject' => '[sitename]: パスワードを忘れた場合',
'password_forgotten_invalid_hash' => '無効なハッシュです',
'password_forgotten_invalid_hash_title' => '無効なハッシュ',
'password_forgotten_send_hash' => '手順を記載したメールをユーザーに送信しました',
'password_forgotten_text' => '以下のフォームに入力し、送信されたメールの指示に従ってください。',
'password_forgotten_title' => 'パスワード送信済み',
'password_mismatch_error' => 'パスワードが一致しません',
'password_mismatch_error_title' => 'パスワードが一致しません',
'password_never_expires' => 'パスワードは期限切れになりません',
'password_repeat' => 'パスワード（確認用）',
'password_send' => 'パスワード送信',
'password_send_text' => '新しいパスワードは、ログインとメールアドレスが既存ユーザーと一致する場合に送信されます。メールが届かない場合は再度確認してお試しください。',
'password_strength' => 'パスワードの強度',
'password_strength_insuffient' => 'パスワードの強度が不十分です',
'password_wrong' => 'パスワードが間違っています',
'pdf_converters' => 'PDF変換',
'pending_approvals' => '承認待ち',
'pending_receipt' => '受領待ち',
'pending_reviews' => 'レビュー待ち',
'pending_revision' => '改訂待ち',
'pending_workflows' => 'ワークフロー待ち',
'personal_default_keywords' => '個人用キーワードリスト',
'php_info' => 'PHP情報',
'pl_PL' => 'ポーランド語',
'possible_substitutes' => '代替',
'preset_expires' => '設定済み有効期限',
'preview' => 'プレビュー',
'preview_converters' => 'ドキュメント変換プレビュー',
'preview_images_text' => '画像とテキストのプレビュー',
'preview_markdown' => 'Markdown',
'preview_pdf' => 'PDFとしてプレビュー',
'preview_plain' => 'テキスト',
'preview_png' => '画像プレビュー',
'preview_txt' => 'テキストプレビュー',
'previous_state' => '前の状態',
'previous_versions' => '以前のバージョン',
'problematic_filename' => 'ファイル名に不正な文字が含まれているか、問題を起こす可能性があります。この名前はダウンロードやWebDAVサーバーで使用されます。',
'process' => '処理',
'process_without_user_group' => 'ユーザー/グループなしの処理',
'pt_BR' => 'ポルトガル語（ブラジル）',
'quota' => 'ディスク容量',
'quota_exceeded' => 'ディスク容量が [bytes] を超えています。',
'quota_is_disabled' => 'ディスク容量制限は無効です。有効にするまで設定しても効果はありません。',
'quota_warning' => '最大ディスク容量を超えています。[bytes] の削除を検討してください。',
'readme_loading' => 'Readmeを読み込み中…',
'receipts_accepted' => '[no_receipts] 件の受領確認済み',
'receipts_accepted_latest' => '(最新バージョンでは [no_receipts] 件)',
'receipts_not_touched' => '[no_receipts] 件の受領未確認',
'receipts_not_touched_latest' => '(最新バージョンでは [no_receipts] 件)',
'receipts_rejected' => '[no_receipts] 件の受領拒否済み',
'receipts_rejected_latest' => '(最新バージョンでは [no_receipts] 件)',
'receipts_without_group' => 'グループなしの受領者',
'receipts_without_user' => 'ユーザーなしの受領者',
'receipt_deletion_email_body' => 'ユーザーは受信者リストから削除されました。

ドキュメント: [name]
バージョン: [version]
親フォルダ: [folder_path]
受信者: [recipient]
ユーザー: [username]
URL: [url]',
'receipt_deletion_email_body_html' => '<p>ユーザーは受信者リストから削除されました。</p>

<p>ドキュメント: [name]<br />
バージョン: [version]<br />
親フォルダ: [folder_path]<br />
受信者: [recipient]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'receipt_deletion_email_subject' => '[sitename]: [name] - 受信者を削除',
'receipt_log' => '受領ログ',
'receipt_request_email_body' => '受領要求

ドキュメント: [name]
バージョン: [version]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'receipt_request_email_body_html' => '<p>受領要求</p>

<p>ドキュメント: [name]<br />
バージョン: [version]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'receipt_request_email_subject' => '[sitename]: [name] - 受領要求',
'receipt_status' => 'ステータス',
'receipt_submit_email_body' => '受領済み

ドキュメント: [name]
バージョン: [version]
ステータス: [status]
コメント: [comment]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'receipt_submit_email_body_html' => '<p>受領済み</p>

<p>ドキュメント: [name]<br />
バージョン: [version]<br />
ステータス: [status]<br />
コメント: [comment]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'receipt_submit_email_subject' => '[sitename]: [name] - 受領済み',
'receipt_summary' => '受領サマリ',
'receipt_update_failed' => '受領の確認に失敗しました',
'recentchanges_mail_subject' => '最近の変更',
'recent_uploads' => '最近のアップロード',
'reception' => '受領',
'reception_acknowleged' => '受領確認済み',
'reception_noaction' => '処理なし',
'reception_rejected' => '受領拒否',
'recipients' => '受信者',
'recipient_already_removed' => '受信者は既に削除済み、または受領確認済みです。',
'record_type' => '種類',
'redraw' => '再描画',
'refresh' => '更新',
'rejected' => '拒否',
'released' => 'リリース済み',
'removed_approver' => '承認者リストから削除されました。',
'removed_file_email' => '添付ファイル削除',
'removed_file_email_body' => '添付ファイルが削除されました

ドキュメント: [document]
ユーザー: [username]
URL: [url]',
'removed_file_email_body_html' => '<p>添付ファイルが削除されました</p>

<p>ドキュメント: [document]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'removed_file_email_subject' => '[sitename]: [document] - 添付ファイル削除',
'removed_recipient' => '受信者リストから削除されました。',
'removed_reviewer' => 'レビュアーリストから削除されました。',
'removed_revisor' => 'レビジョン担当者リストから削除されました。',
'removed_workflow_email_body' => 'ドキュメントバージョンからワークフローが削除されました。

ドキュメント: [name]
バージョン: [version]
ワークフロー: [workflow]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'removed_workflow_email_body_html' => '<p>ドキュメントバージョンからワークフローが削除されました。</p>

<p>ドキュメント: [name]<br />
バージョン: [version]<br />
ワークフロー: [workflow]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'removed_workflow_email_subject' => '[sitename]: [name] - ワークフロー削除',
'removeFolderFromDropFolder' => 'インポート後にフォルダを削除',
'removeFolderFromDropFolder_desc' => 'インポート後にドロップフォルダからフォルダを削除する場合に有効にしてください。',
'remove_approval_log' => '承認削除',
'remove_from_clipboard' => 'クリップボードから削除',
'remove_marked_files' => 'マークされたファイルを削除',
'remove_review_log' => 'レビュー削除',
'remove_task' => 'タスク削除',
'reorder' => '順序変更',
'reorder_documents_in_folder' => 'フォルダ内の全ドキュメントに1.0から順序番号を再割り当て',
'repaired' => '修復済み',
'repairing_objects' => 'ドキュメントとフォルダを修復中',
'replace_content_email_body' => 'ドキュメントの最新バージョンが置き換えられました。

ドキュメント: [name]
バージョン: [version]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'replace_content_email_body_html' => '<p>ドキュメントの最新バージョンが置き換えられました。</p>

<p>ドキュメント: [name]<br />
バージョン: [version]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'replace_content_email_subject' => '[sitename]: [name] - ドキュメント内容置き換え',
'request_workflow_action_email_body' => 'ワークフローがあなたの操作を必要とする状態になりました。

ドキュメント: [name]
バージョン: [version]
ワークフロー: [workflow]
現在の状態: [current_state]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'request_workflow_action_email_body_html' => '<p>ワークフローがあなたの操作を必要とする状態になりました。</p>

<p>ドキュメント: [name]<br />
バージョン: [version]<br />
ワークフロー: [workflow]<br />
現在の状態: [current_state]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'request_workflow_action_email_subject' => '[sitename]: [name] - ワークフロー操作が必要',
'reset_checkout' => 'チェックアウト終了',
'restrict_access' => 'アクセス不可',
'results_page' => '検索結果ページ',
'return_from_subworkflow' => 'サブワークフローからの戻り',
'return_from_subworkflow_email_body' => 'サブワークフローから戻りました

ドキュメント: [name]
バージョン: [version]
ワークフロー: [workflow]
サブワークフロー: [subworkflow]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'return_from_subworkflow_email_body_html' => '<p>サブワークフローから戻りました</p>

<p>ドキュメント: [name]<br />
バージョン: [version]<br />
ワークフロー: [workflow]<br />
サブワークフロー: [subworkflow]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'return_from_subworkflow_email_subject' => '[sitename]: [name] - サブワークフローから戻り',
'reverse_links' => '現在のドキュメントにリンクしているドキュメント',
'reviewers' => 'レビュアー',
'reviewer_already_assigned' => 'ユーザーは既にレビュアーとして割り当てられています',
'reviewer_already_removed' => 'レビュアーは既にレビューから削除されているか、レビューを提出済みです',
'reviews_accepted' => '[no_reviews] 件のレビューは既に承認済み',
'reviews_accepted_latest' => '(最新バージョンで [no_reviews] 件)',
'reviews_not_touched' => '[no_reviews] 件のレビューは未処理',
'reviews_not_touched_latest' => '(最新バージョンで [no_reviews] 件)',
'reviews_rejected' => '[no_reviews] 件のレビューは既に拒否済み',
'reviews_rejected_latest' => '(最新バージョンで [no_reviews] 件)',
'reviews_without_group' => 'グループなしのレビュー',
'reviews_without_user' => 'ユーザーなしのレビュー',
'review_deletion_email' => 'レビュー要求削除',
'review_deletion_email_body' => 'レビュー要求が削除されました

ドキュメント: [name]
バージョン: [version]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'review_deletion_email_body_html' => '<p>レビュー要求が削除されました</p>

<p>ドキュメント: [name]<br />
バージョン: [version]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'review_deletion_email_subject' => '[sitename]: [name] - レビュー要求削除',
'review_file' => 'ファイル',
'review_group' => 'レビューグループ',
'review_log' => 'レビュー履歴',
'review_request_email' => 'レビュー要求',
'review_request_email_body' => 'レビュー要求

ドキュメント: [name]
バージョン: [version]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'review_request_email_body_html' => '<p>レビュー要求</p>

<p>ドキュメント: [name]<br />
バージョン: [version]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'review_request_email_subject' => '[sitename]: [name] - レビュー要求',
'review_status' => 'レビュー状況',
'review_submit_email' => 'レビュー提出済み',
'review_submit_email_body' => 'レビュー提出済み

ドキュメント: [name]
バージョン: [version]
ステータス: [status]
コメント: [comment]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'review_submit_email_body_html' => '<p>レビュー提出済み</p>

<p>ドキュメント: [name]<br />
バージョン: [version]<br />
ステータス: [status]<br />
コメント: [comment]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'review_submit_email_subject' => '[sitename]: [name] - レビュー提出済み',
'review_summary' => 'レビューサマリ',
'review_update_failed' => 'レビュー状況の更新に失敗しました',
'revise_document' => 'ドキュメントを改訂',
'revise_document_on' => '[date] にドキュメントの次の改訂',
'revision' => '改訂',
'revisions_accepted' => '[no_revisions] 件の改訂は既に承認済み',
'revisions_accepted_latest' => '(最新バージョンで [no_revisions] 件)',
'revisions_not_touched' => '[no_revisions] 件の改訂は未処理',
'revisions_not_touched_latest' => '(最新バージョンで [no_revisions] 件)',
'revisions_pending' => '[no_revisions] 件の改訂が将来予定',
'revisions_pending_latest' => '(最新バージョンで [no_revisions] 件)',
'revisions_rejected' => '[no_revisions] 件の改訂は既に拒否済み',
'revisions_rejected_latest' => '(最新バージョンで [no_revisions] 件)',
'revisions_without_group' => 'グループなしの改訂',
'revisions_without_user' => 'ユーザーなしの改訂',
'revision_date' => '改訂日',
'revision_deletion_email_body' => '<p>改訂要求が削除されました</p>

<p>ドキュメント: [name]<br />
バージョン: [version]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'revision_deletion_email_subject' => '[sitename]: [name] - 改訂要求削除',
'revision_log' => '改訂履歴',
'revision_request_email_body' => '改訂要求

ドキュメント: [name]
バージョン: [version]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'revision_request_email_body_html' => '<p>改訂要求</p>

<p>ドキュメント: [name]<br />
バージョン: [version]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'revision_request_email_subject' => '[sitename]: [name] - 改訂要求',
'revision_status' => 'ステータス',
'revision_submit_email_body' => '改訂提出済み

ドキュメント: [name]
バージョン: [version]
ステータス: [status]
コメント: [comment]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'revision_submit_email_body_html' => '<p>改訂提出済み</p>

<p>ドキュメント: [name]<br />
バージョン: [version]<br />
ステータス: [status]<br />
コメント: [comment]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'revision_submit_email_subject' => '[sitename]: [name] - 改訂提出済み',
'revision_summary' => '改訂',
'revisors' => 'レビジョン担当者',
'revisor_already_assigned' => 'ユーザーは既にレビジョン担当者として割り当てられています。',
'revisor_already_removed' => 'レビジョン担当者は既に改訂プロセスから削除されているか、ドキュメントを既に改訂済みです。',
'rewind_workflow' => 'ワークフローを巻き戻す',
'rewind_workflow_email_body' => 'ワークフローが巻き戻されました

ドキュメント: [name]
バージョン: [version]
ワークフロー: [workflow]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'rewind_workflow_email_body_html' => '<p>ワークフローが巻き戻されました</p>

<p>ドキュメント: [name]<br />
バージョン: [version]<br />
ワークフロー: [workflow]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'rewind_workflow_email_subject' => '[sitename]: [name] - ワークフローが巻き戻されました',
'rewind_workflow_warning' => 'ワークフローを初期状態に巻き戻すと、このドキュメントのワークフロー履歴全体が削除され、復元できなくなります。',
'rm_attrdef' => '属性定義を削除',
'rm_attrdefgroup' => 'この属性グループを削除',
'rm_attr_value' => '値を削除',
'rm_default_keyword_category' => 'カテゴリを削除',
'rm_document' => 'ドキュメントを削除',
'rm_document_category' => 'カテゴリを削除',
'rm_event' => 'イベントを削除',
'rm_file' => 'ファイルを削除',
'rm_folder' => 'フォルダを削除',
'rm_from_clipboard' => 'クリップボードから削除',
'rm_group' => 'このグループを削除',
'rm_role' => 'この役割を削除',
'rm_task' => 'タスクを削除',
'rm_transmittal' => '回覧を削除',
'rm_transmittalitem' => 'アイテムを削除',
'rm_user' => 'ユーザーを削除',
'rm_user_from_processes' => 'プロセスからユーザーを削除',
'rm_version' => 'バージョンを削除',
'rm_workflow' => 'ワークフローを削除',
'rm_workflow_action' => 'ワークフローアクションを削除',
'rm_workflow_state' => 'ワークフロー状態を削除',
'rm_workflow_warning' => 'この操作を行うとドキュメントからワークフローが削除されます。元に戻すことはできません。',
'role' => '役割',
'role_admin' => '管理者',
'role_guest' => 'ゲスト',
'role_info' => '情報',
'role_management' => '役割管理',
'role_name' => '名前',
'role_type' => '役割の種類',
'role_user' => 'ユーザー',
'ro_RO' => 'ルーマニア語',
'run_subworkflow' => 'サブワークフローを実行',
'run_subworkflow_email_body' => 'サブワークフローが開始されました

ドキュメント: [name]
バージョン: [version]
ワークフロー: [workflow]
サブワークフロー: [subworkflow]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'run_subworkflow_email_body_html' => '<p>サブワークフローが開始されました</p>

<p>ドキュメント: [name]<br />
バージョン: [version]<br />
ワークフロー: [workflow]<br />
サブワークフロー: [subworkflow]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'run_subworkflow_email_subject' => '[sitename]: [name] - サブワークフローが開始されました',
'ru_RU' => 'ロシア語',
'saturday' => '土曜日',
'saturday_abbr' => '土',
'save' => '保存',
'scheduler_class' => 'クラス',
'scheduler_class_description' => '説明',
'scheduler_class_parameter' => 'パラメータ',
'scheduler_class_tasks' => 'クラスのタスク',
'scheduler_task_mgr' => 'スケジューラ',
'search' => '検索',
'search_fulltext' => '全文検索',
'search_in' => '検索対象',
'search_mode' => '検索モード',
'search_mode_and' => 'すべての単語',
'search_mode_documents' => 'ドキュメントのみ',
'search_mode_folders' => 'フォルダのみ',
'search_mode_or' => 'いずれかの単語',
'search_no_results' => '検索に一致するドキュメントはありません',
'search_query' => '検索ワード',
'search_query_placeholder' => 'タイトル、コメント、キーワード、内容を検索',
'search_report' => '[doccount] 件のドキュメントと [foldercount] 件のフォルダを [searchtime] 秒で検索しました。',
'search_report_fulltext' => '[doccount] 件のドキュメントを検索しました',
'search_resultmode' => '検索結果',
'search_resultmode_both' => 'ドキュメントとフォルダ',
'search_results' => '検索結果',
'search_results_access_filtered' => '検索結果にはアクセスが拒否された内容が含まれる場合があります。',
'search_time' => '経過時間: [time] 秒',
'seconds' => '秒',
'seeddms_info' => 'SeedDMSについての情報',
'seeddms_version' => 'SeedDMSのバージョン',
'selection' => '選択',
'select_attrdef' => '属性定義を選択',
'select_attrdefgrp_show' => '表示タイミングを選択',
'select_attribute_value' => '属性値を選択',
'select_category' => 'カテゴリを選択',
'select_created' => '作成日を選択',
'select_documents_for_process' => 'ドキュメントを選択',
'select_folder' => 'フォルダを選択',
'select_group' => 'グループを選択',
'select_groups' => 'グループを選択',
'select_grp_approvers' => '承認者グループを選択',
'select_grp_ind_approvers' => 'グループを選択',
'select_grp_ind_notification' => 'グループを選択',
'select_grp_ind_recipients' => 'グループを選択',
'select_grp_ind_reviewers' => 'グループを選択',
'select_grp_ind_revisors' => 'グループを選択',
'select_grp_notification' => '通知グループを選択',
'select_grp_recipients' => '受信者グループを選択',
'select_grp_reviewers' => 'レビュアーグループを選択',
'select_grp_revisors' => 'レビジョン担当者グループを選択',
'select_ind_approvers' => '個別承認者を選択',
'select_ind_notification' => '個別通知を選択',
'select_ind_recipients' => '個別受信者を選択',
'select_ind_reviewers' => '個別レビュアーを選択',
'select_ind_revisors' => '個別レビジョン担当者を選択',
'select_mimetype' => 'MIMEタイプを選択',
'select_modified' => '変更日を選択',
'select_one' => '1つ選択',
'select_option' => 'オプションを選択',
'select_owner' => '所有者を選択',
'select_record_type' => 'タイプを選択',
'select_status' => 'ドキュメントのステータスを選択',
'select_user' => 'ユーザーを選択',
'select_users' => 'ユーザーを選択',
'select_value' => '値を選択',
'select_workflow' => 'ワークフローを選択',
'send_email' => 'メール送信',
'send_login_data' => 'ログイン情報を送信',
'send_login_data_body' => 'ログイン情報

ログイン: [login]
名前: [username]

[comment]

パスワードを受け取っていない場合は、ログインページの「パスワードを忘れた場合」機能で新しいパスワードを設定してください。',
'send_login_data_subject' => '[sitename]: [login] - ログイン情報',
'send_notification' => '通知を送信',
'send_test_mail' => 'テストメール送信',
'september' => '9月',
'sequence' => '順序',
'seq_after' => '"[prevname]" の後',
'seq_end' => '最後に追加',
'seq_keep' => '位置を保持',
'seq_start' => '最初に追加',
'service_has_filter' => 'サービスにフィルタがあります',
'service_list_from' => '開始',
'service_list_info' => '情報',
'service_list_to' => '終了',
'service_name' => 'サービス名',
'sessions' => 'オンラインユーザー',
'setDateFromFile' => 'インポートしたファイルから日付を取得',
'setDateFromFile_desc' => 'インポートしたファイルの日付をSeedDMSのドキュメント日付として使用',
'setDateFromFolder' => 'インポートしたフォルダから日付を取得',
'setDateFromFolder_desc' => 'インポートしたディレクトリの日付をSeedDMSのフォルダ日付として使用',
'settings' => '設定',
'settings_activate_module' => 'モジュールを有効化',
'settings_activate_php_extension' => 'PHP拡張を有効化',
'settings_addManagerAsApprover' => 'グループマネージャーを承認者に追加',
'settings_addManagerAsApprover_desc' => 'ユーザーがアップロードしたすべての文書は、そのユーザーが所属するグループのマネージャーによって承認されます。',
'settings_addManagerAsReviewer' => 'グループマネージャーをレビュー担当に追加',
'settings_addManagerAsReviewer_desc' => 'ユーザーがアップロードしたすべての文書は、そのユーザーが所属するグループのマネージャーによってレビューされます。',
'settings_adminIP' => '管理者IP',
'settings_adminIP_desc' => '設定すると、管理者は指定されたIPアドレスからのみログイン可能です。空欄にするとアクセス制限は適用されません。注：ローカル認証（LDAP未使用）の場合のみ有効です。',
'settings_Advanced' => '詳細設定',
'settings_advancedAcl' => '高度なアクセス制御',
'settings_advancedAcl_desc' => '高度なアクセス制御により、ソフトウェアの特定モジュールのON/OFFが可能になります。文書やフォルダへのアクセス権には使用できません。',
'settings_allowChangeRevAppInProcess' => '処理中のレビュー/承認者変更を許可',
'settings_allowChangeRevAppInProcess_desc' => '通常、一度レビューや承認が送信された後は、レビュー担当者や承認者を変更できません。このオプションを有効にすると、文書が承認または却下されるまで管理者は変更可能です。',
'settings_allowReviewerOnly' => 'レビュー担当のみ設定を許可',
'settings_allowReviewerOnly_desc' => '伝統的ワークフローモードで、承認者なしでレビュー担当者のみを設定できるようにする場合は有効にします。',
'settings_alwaysShowClipboard' => 'メインメニューに常にクリップボードを表示',
'settings_alwaysShowClipboard_desc' => 'クリップボードが空でも、メインメニューにクリップボード項目を表示します。',
'settings_alwaysShowMenuTasks' => 'メインメニューに常にタスクを表示',
'settings_alwaysShowMenuTasks_desc' => '期限のあるタスクがなくても、メインメニューにタスクメニューを表示します。',
'settings_apache_mod_rewrite' => 'Apache - Rewriteモジュール',
'settings_apiKey' => 'REST API認証キー',
'settings_apiKey_desc' => 'REST APIの代替認証として使用するキーです。32文字の文字列を指定してください。',
'settings_apiOrigin' => 'API呼び出しの許可元',
'settings_apiOrigin_desc' => 'セミコロンで区切ったアドレスのリスト。各アドレスは <protocol>://<domain>[:<port>] の形式です。ポートは省略可能です。空欄の場合は制限は適用されません。',
'settings_apiUserId' => 'REST API用ユーザー',
'settings_apiUserId_desc' => 'APIキーで認証した場合、このユーザーがREST APIで使用されます。',
'settings_Authentication' => '認証設定',
'settings_autoLoginUser' => '自動ログイン',
'settings_autoLoginUser_desc' => 'ユーザーが未ログインの場合に使用するユーザーIDです。このアクセスではセッションは作成されません。',
'settings_available_languages' => '利用可能な言語',
'settings_available_languages_desc' => '選択された言語のみが読み込まれ、言語選択に表示されます。デフォルト言語は常に読み込まれます。',
'settings_backupDir' => 'バックアップディレクトリ',
'settings_backupDir_desc' => 'バックアップツールがバックアップを保存するディレクトリです。設定されていない場合やアクセスできない場合は、コンテンツディレクトリに保存されます。',
'settings_baseUrl' => 'ベースURL',
'settings_baseUrl_desc' => 'HTTPルートディレクトリなしのURLです。通常はSeedDMSが自動設定しますが、プロキシ環境では手動設定が必要になることがあります。',
'settings_batchOperations' => '許可する一括操作',
'settings_batchOperations_desc' => '検索結果に対して許可される一括操作です。エクスポートを除き、他の操作は管理者権限が必要です。',
'settings_cacheDir' => 'キャッシュディレクトリ',
'settings_cacheDir_desc' => 'プレビュー画像を保存する場所です（ウェブサーバーからアクセスできないディレクトリを推奨）',
'settings_Calendar' => 'カレンダー設定',
'settings_calendarDefaultView' => 'カレンダーのデフォルト表示',
'settings_calendarDefaultView_desc' => 'カレンダーの初期表示形式です。',
'settings_cannot_disable' => 'ENABLE_INSTALL_TOOL ファイルを削除できませんでした',
'settings_checkOutDir' => 'チェックアウト用ディレクトリ',
'settings_checkOutDir_desc' => '文書がチェックアウトされた場合に最新の内容をコピーするディレクトリです。ユーザーが編集してチェックインできるようにする場合は、ユーザーがアクセス可能な場所にします。',
'settings_cmdTimeout' => '外部コマンドのタイムアウト',
'settings_cmdTimeout_desc' => '外部コマンド（例：全文検索インデックス作成）が終了とみなされるまでの秒数です。',
'settings_conf_field_not_editable' => 'この値は編集できません',
'settings_contentDir' => 'コンテンツディレクトリ',
'settings_contentDir_desc' => 'アップロードされたファイルの保存先です（ウェブサーバーからアクセスできないディレクトリを推奨）',
'settings_contentOffsetDir' => 'コンテンツオフセットディレクトリ',
'settings_contentOffsetDir_desc' => 'ファイルシステムの制限を回避するための新しいディレクトリ構造です。通常はデフォルトの1048576のままで問題ありません。',
'settings_convertToPdf' => 'プレビュー用にPDFに変換',
'settings_convertToPdf_desc' => 'ブラウザで直接表示できない文書は、PDFに変換して表示します。',
'settings_cookieLifetime' => 'クッキーの有効期間',
'settings_cookieLifetime_desc' => 'クッキーの有効期間（秒単位）。0にするとブラウザ終了時に削除されます。',
'settings_coreDir' => 'SeedDMSコアディレクトリ',
'settings_coreDir_desc' => 'SeedDMS_Coreへのパス（任意）。PHPが見つけられる場所にインストールしている場合は空欄でOKです。',
'settings_createCheckOutDir' => 'チェックアウトディレクトリを作成',
'settings_createCheckOutDir_desc' => '存在しない場合はチェックアウトディレクトリを作成します。',
'settings_createdatabase' => 'データベーステーブルを作成',
'settings_createdirectory' => 'ディレクトリを作成',
'settings_currentvalue' => '現在の値',
'settings_Database' => 'データベース設定',
'settings_dateformat' => '日付形式',
'settings_dateformat_desc' => 'PHPのdate()関数の形式を使用します。',
'settings_datetimeformat' => '日付/時刻形式',
'settings_datetimeformat_desc' => 'PHPのdate()関数の形式を使用します。',
'settings_daysPastDashboard' => 'ダッシュボードに表示する過去日数',
'settings_daysPastDashboard_desc' => 'ダッシュボードで文書を一覧表示する際に考慮する過去の日数です。',
'settings_dbDatabase' => 'データベース',
'settings_dbDatabase_desc' => 'インストール時に設定したデータベース名です。必要がない限り編集しないでください。',
'settings_dbDriver' => 'データベース種類',
'settings_dbDriver_desc' => 'インストール時に使用したデータベースの種類です。ホスト変更などの場合のみ編集してください。',
'settings_dbHostname' => 'サーバー名',
'settings_dbHostname_desc' => 'インストール時に設定したデータベースサーバーのホスト名です。必要がない限り編集しないでください。',
'settings_dbPass' => 'パスワード',
'settings_dbPass_desc' => 'データベースアクセス用のパスワードです。',
'settings_dbUser' => 'ユーザー名',
'settings_dbUser_desc' => 'データベースアクセス用のユーザー名です。',
'settings_dbVersion' => 'データベーススキーマが古すぎます',
'settings_defaultAccessDocs' => '新規文書のデフォルトアクセス権',
'settings_defaultAccessDocs_desc' => '新しい文書作成時のデフォルトアクセス権です。',
'settings_defaultDocPosition' => '文書作成時の位置',
'settings_defaultDocPosition_desc' => '新しい文書作成時のフォルダ内のデフォルト位置です。',
'settings_defaultDocPosition_val_end' => '末尾',
'settings_defaultDocPosition_val_start' => '先頭',
'settings_defaultFolderPosition' => 'フォルダ作成時の位置',
'settings_defaultFolderPosition_desc' => '新しいフォルダ作成時のフォルダ内のデフォルト位置です。',
'settings_defaultSearchMethod' => 'デフォルト検索方法',
'settings_defaultSearchMethod_desc' => 'メインメニューの検索フォームから検索を開始する際のデフォルト方法です。',
'settings_defaultSearchMethod_valdatabase' => 'データベース',
'settings_defaultSearchMethod_valfulltext' => '全文検索',
'settings_defaultThumbnailClick' => 'サムネイルクリック時の動作',
'settings_defaultThumbnailClick_desc' => 'サムネイルをクリックした際に実行される動作です。',
'settings_defaultThumbnailClick_valdownload' => '文書をダウンロード',
'settings_defaultThumbnailClick_valviewonline' => '文書をオンラインで表示',
'settings_delete_install_folder' => 'SeedDMSを使用するには、設定ディレクトリ内の ENABLE_INSTALL_TOOL を削除してください。',
'settings_disableChangePassword' => 'パスワード変更を禁止',
'settings_disableChangePassword_desc' => 'LDAP認証を使用する場合に有効にします。データベースのパスワード設定やLDAP回避を防ぎます。',
'settings_disableReceiptComment' => '受領コメントを無効化',
'settings_disableReceiptComment_desc' => '有効にすると、受領時のコメント入力が無効になります。',
'settings_disableSelfEdit' => '自己編集を無効化',
'settings_disableSelfEdit_desc' => '有効にすると、ユーザーは自分のプロフィールを編集できません。',
'settings_disable_install' => 'ENABLE_INSTALL_TOOL を削除可能なら削除',
'settings_Display' => '表示設定',
'settings_dropFolderDir' => 'ドロップフォルダ用ディレクトリ',
'settings_dropFolderDir_desc' => 'サーバーファイルシステムにファイルを置き、ブラウザアップロードの代わりにインポート可能です。ユーザーごとにサブディレクトリを作成してください。',
'settings_Edition' => 'エディション設定',
'settings_editOnlineFileTypes' => 'オンライン編集可能なファイルタイプ',
'settings_editOnlineFileTypes_desc' => '以下の拡張子またはMIMEタイプのファイルをオンラインで編集可能です（小文字のみ使用）。',
'settings_enable2FactorAuthentication' => '二要素認証を有効化',
'settings_enable2FactorAuthentication_desc' => '有効にすると、ユーザーはスマートフォンのGoogle Authenticatorを使用する必要があります。',
'settings_enableAcknowledgeWorkflow' => '受領確認ワークフローを有効化',
'settings_enableAcknowledgeWorkflow_desc' => '受領確認のワークフローを有効化します。',
'settings_enableAdminReceipt' => '管理者の受領を許可',
'settings_enableAdminReceipt_desc' => '有効にすると、管理者も文書の受領者としてリストされます。',
'settings_enableAdminRevApp' => '管理者のレビュー/承認を許可',
'settings_enableAdminRevApp_desc' => '有効にすると、管理者もレビュー担当者や承認者としてリストされ、ワークフローの遷移に参加できます。',
'settings_enableCalendar' => 'カレンダーを有効化',
'settings_enableCalendar_desc' => 'カレンダーを有効/無効にします。',
'settings_enableCancelCheckout' => 'チェックアウトキャンセルを許可',
'settings_enableCancelCheckout_desc' => '有効にすると、チェックアウト済みの文書を破棄できます。',
'settings_enableClipboard' => 'クリップボードを有効化',
'settings_enableClipboard_desc' => '\'フォルダ表示\'ページでクリップボードを有効/無効にします。',
'settings_enableConverting' => 'ファイル変換を有効化',
'settings_enableConverting_desc' => 'ファイルの変換を有効/無効にします。',
'settings_enableDebugMode' => 'デバッグモード',
'settings_enableDebugMode_desc' => '有効にすると、管理ツールに新しいメニューが追加されます。',
'settings_enableDropFolderList' => 'メニューにドロップフォルダ一覧を表示',
'settings_enableDropFolderList_desc' => 'ドロップフォルダ内のファイル一覧をメインメニューに表示します。',
'settings_enableDropUpload' => '高速アップロードを有効化',
'settings_enableDropUpload_desc' => '\'フォルダ表示\'ページでドラッグ＆ドロップによるアップロードを有効/無効にします。',
'settings_enableDuplicateDocNames' => '同名文書を許可',
'settings_enableDuplicateDocNames_desc' => 'フォルダ内で同名文書を許可します。',
'settings_enableDuplicateSubFolderNames' => '同名サブフォルダを許可',
'settings_enableDuplicateSubFolderNames_desc' => 'フォルダ内で同名サブフォルダを許可します。',
'settings_enableEmail' => 'メール通知を有効化',
'settings_enableEmail_desc' => '自動メール通知を有効/無効にします。',
'settings_enableExtensionDownload' => '拡張機能のダウンロードを許可',
'settings_enableExtensionDownload_desc' => '有効にすると、拡張機能マネージャーでダウンロード可能になります。',
'settings_enableExtensionImport' => '拡張機能のインポートを許可',
'settings_enableExtensionImportFromRepository' => 'リポジトリからの拡張機能インポートを許可',
'settings_enableExtensionImportFromRepository_desc' => 'リポジトリから拡張機能をインポート可能にします。',
'settings_enableExtensionImport_desc' => '有効にすると、拡張機能マネージャーにアップロードしてインポート可能になります。',
'settings_enableFilterReceipt' => '受領リストで所有者やレビュー担当を除外',
'settings_enableFilterReceipt_desc' => 'グループ選択時に受領リストから特定の受領者を除外する場合に有効にします。',
'settings_enableFolderTree' => 'フォルダツリーを有効化',
'settings_enableFolderTree_desc' => '\'フォルダ表示\'ページでフォルダツリーを有効/無効にします。',
'settings_enableFullSearch' => '全文検索を有効化',
'settings_enableFullSearch_desc' => '全文検索を有効/無効にします。',
'settings_enableGuestAutoLogin' => 'ゲスト自動ログインを有効化',
'settings_enableGuestAutoLogin_desc' => 'ゲストログインと自動ログインが有効な場合、ゲストは自動的にログインされます。',
'settings_enableGuestLogin' => 'ゲストログインを有効化',
'settings_enableGuestLogin_desc' => '誰でもゲストとしてログインできるようにする場合にチェックします。信頼できる環境でのみ使用してください。',
'settings_enableHelp' => 'ヘルプを有効化',
'settings_enableHelp_desc' => 'メニューにヘルプ画面へのリンクを表示/非表示にします。',
'settings_enableHiddenReceipt' => '非表示ユーザーの受領を許可',
'settings_enableHiddenReceipt_desc' => '有効にすると、非表示ユーザーも文書の受領者としてリストされます。',
'settings_enableHiddenRevApp' => '非表示ユーザーのレビュー/承認を許可',
'settings_enableHiddenRevApp_desc' => '有効にすると、非表示ユーザーもレビュー担当者や承認者としてリストされ、ワークフローに参加できます。',
'settings_enableLanguageSelector' => '言語選択を有効化',
'settings_enableLanguageSelector_desc' => 'ログイン後、UI言語を選択できるようにします。',
'settings_enableLargeFileUpload' => '大容量ファイルアップロードを有効化',
'settings_enableLargeFileUpload_desc' => 'Javaアプレット（Jumploader）を使用し、ブラウザの制限なしで複数ファイルをアップロード可能にします。HTTPのみのクッキーは無効になります。',
'settings_enableLoginByEmail' => 'メールアドレスでログインを有効化',
'settings_enableLoginByEmail_desc' => '有効にすると、ユーザーはメールアドレスでもログイン可能です。すべての認証方法で機能するとは限りません。',
'settings_enableMemcached' => 'Memcachedを使用（実験的）',
'settings_enableMemcached_desc' => '一部のデータベース操作を高速化するためにMemcachedを使用します。運用環境では推奨されません。',
'settings_enableMenuTasks' => 'メニューにタスクリストを表示',
'settings_enableMenuTasks_desc' => 'ユーザーのタスク（レビュー、承認等）を含むメニュー項目を表示します。',
'settings_enableMenuTransmittals' => 'メニューに伝送文書を表示',
'settings_enableMenuTransmittals_desc' => 'ユーザーの伝送文書を含むメニュー項目を表示します。',
'settings_enableMultiUpload' => '複数ファイルアップロードを許可',
'settings_enableMultiUpload_desc' => '新規文書作成時に複数ファイルをアップロード可能にし、それぞれ新しい文書として登録されます。',
'settings_enableNotificationAppRev' => 'レビュー/承認通知を有効化',
'settings_enableNotificationAppRev_desc' => '新しい文書バージョンが追加されたときにレビュー担当者/承認者へ通知を送信します。',
'settings_enableNotificationWorkflow' => 'ワークフロー次ステップで通知を送信',
'settings_enableNotificationWorkflow_desc' => '有効にすると、次のワークフローでアクションが必要なユーザーやグループに通知が送信されます。',
'settings_enableOwnerNotification' => '所有者への通知をデフォルトで有効化',
'settings_enableOwnerNotification_desc' => '文書追加時に所有者に通知を追加します。',
'settings_enableOwnerReceipt' => '所有者の受領を許可',
'settings_enableOwnerReceipt_desc' => '有効にすると、文書の所有者も受領者としてリストされます。',
'settings_enableOwnerRevApp' => '所有者のレビュー/承認を許可',
'settings_enableOwnerRevApp_desc' => '有効にすると、文書の所有者もレビュー担当者/承認者としてリストされ、ワークフローに参加できます。',
'settings_enablePasswordForgotten' => 'パスワード忘れを有効化',
'settings_enablePasswordForgotten_desc' => '有効にすると、ユーザーはパスワードをリセットしてメール送信できます。',
'settings_enableReceiptReject' => '受領拒否を有効化',
'settings_enableReceiptReject_desc' => '有効にすると、受領を拒否可能になります。',
'settings_enableReceiptWorkflow' => '文書受領確認ワークフローを有効化',
'settings_enableReceiptWorkflow_desc' => '文書受領の承認ワークフローを有効化します。',
'settings_enableRecursiveCount' => '再帰的な文書/フォルダ数カウントを有効化',
'settings_enableRecursiveCount_desc' => '有効にすると、フォルダ内の文書とフォルダの数を、アクセス可能なすべてのサブフォルダを再帰的にカウントして算出します。',
'settings_enableRemoveRevApp' => '既存のレビュー/承認の削除を許可',
'settings_enableRemoveRevApp_desc' => '有効にすると、管理者がレビュー/承認を削除可能です。データベースの削除ではなく、レビュー/承認ログに初期状態として追加されます。',
'settings_enableRevisionOneVoteReject' => '1人のレビュアーによる却下を有効化',
'settings_enableRevisionOneVoteReject_desc' => '有効にすると、最初のレビュアーが文書を却下した時点で文書ステータスが「修正必要」に設定されます。',
'settings_enableRevisionOnVoteReject' => '投票による修正ワークフローを有効化',
'settings_enableRevisionOnVoteReject_desc' => '有効にすると、投票での修正ワークフローが開始されます。',
'settings_enableRevisionWorkflow' => '文書修正ワークフローを有効化',
'settings_enableRevisionWorkflow_desc' => '有効にすると、指定期間後に文書修正のワークフローを実行可能になります。',
'settings_enableSelfReceipt' => 'ログインユーザーの受領を許可',
'settings_enableSelfReceipt_desc' => '有効にすると、ログイン中のユーザーが文書の受領者としてリストされます。',
'settings_enableSelfRevApp' => 'ログインユーザーによるレビュー/承認を許可',
'settings_enableSelfRevApp_desc' => '有効にすると、ログイン中のユーザーがレビュー担当者/承認者としてリストされ、ワークフローに参加できます。',
'settings_enableSessionList' => 'メニューにオンラインユーザーリストを表示',
'settings_enableSessionList_desc' => '現在ログインしているユーザーのリストをメニューに表示します。',
'settings_enableThemeSelector' => 'テーマ選択',
'settings_enableThemeSelector_desc' => 'ログインページでテーマ選択を有効/無効にします。',
'settings_enableUpdateReceipt' => '既存受領の編集を許可',
'settings_enableUpdateReceipt_desc' => '有効にすると、受領を行ったユーザーが決定を変更可能です。',
'settings_enableUpdateRevApp' => '既存レビュー/承認の編集を許可',
'settings_enableUpdateRevApp_desc' => '有効にすると、レビュー/承認を行ったユーザーが、現在のワークフローが終了するまで決定を変更可能です。',
'settings_enableUserImage' => 'ユーザー画像を有効化',
'settings_enableUserImage_desc' => 'ユーザー画像を有効にします。',
'settings_enableUsersView' => 'ユーザー表示を有効化',
'settings_enableUsersView_desc' => 'グループ・ユーザー表示を全ユーザーに有効/無効にします。',
'settings_enableVersionDeletion' => '以前のバージョン削除を有効化',
'settings_enableVersionDeletion_desc' => '通常ユーザーによる古い文書バージョンの削除を有効/無効にします。管理者は常に削除可能です。',
'settings_enableVersionModification' => 'バージョン編集を有効化',
'settings_enableVersionModification_desc' => 'アップロード後の文書バージョンを通常ユーザーが編集できるかどうかを設定します。管理者は常に編集可能です。',
'settings_enableWebdavReplaceDoc' => '保存時に文書を置換',
'settings_enableWebdavReplaceDoc_desc' => '有効にすると、新しいバージョン保存時に既存文書を置換します（ユーザー、MIMEタイプ、ファイル名が前バージョンと同一の場合）。自動保存用途に便利です。',
'settings_enableXsendfile' => 'Apache X-Sendfileモジュールを使用',
'settings_enableXsendfile_desc' => '有効にすると、ApacheモジュールX-Sendfileを使用して画像を配信します。',
'settings_encryptionKey' => '暗号化キー',
'settings_encryptionKey_desc' => 'この文字列は、CSRF攻撃を防ぐためにフォームに隠しフィールドとして追加される一意の識別子を作成する際に使用されます。',
'settings_error' => 'エラー',
'settings_excludeFoldersDashboard' => 'ダッシュボードからフォルダを除外',
'settings_excludeFoldersDashboard_desc' => 'このフォルダ内の文書はダッシュボードに表示されません。アーカイブ済みやゴミ箱内の文書に有用です。',
'settings_expandFolderTree' => 'フォルダツリーを展開',
'settings_expandFolderTree_desc' => 'フォルダツリーを展開',
'settings_expandFolderTree_val0' => 'ツリーを非表示で開始',
'settings_expandFolderTree_val1' => 'ツリーを表示し、最初の階層を展開して開始',
'settings_expandFolderTree_val2' => 'ツリーを完全に展開して開始',
'settings_ExtensionMgr' => '拡張機能管理設定',
'settings_Extensions' => '拡張機能',
'settings_extraPath' => '追加のPHPインクルードパス',
'settings_extraPath_desc' => '追加ソフトウェアへのパス。例：adodbディレクトリや追加のPEARパッケージを含むディレクトリ',
'settings_firstDayOfWeek' => '週の開始日',
'settings_firstDayOfWeek_desc' => '週の最初の日',
'settings_footNote' => 'フッターノート',
'settings_footNote_desc' => '全ページの下部に表示するメッセージ',
'settings_fullSearchEngine' => '全文検索エンジン',
'settings_fullSearchEngine_desc' => '全文検索に使用する方法を設定します。',
'settings_fullSearchEngine_vallucene' => 'Zend Lucene',
'settings_fullSearchEngine_valsqlitefts' => 'SQLiteFTS',
'settings_globalApprover' => '全文書の承認者を追加',
'settings_globalApprover_desc' => 'アップロードされたすべての文書に必須承認者として追加されるユーザーです。',
'settings_globalGroupApprover' => '全文書のグループ承認者を追加',
'settings_globalGroupApprover_desc' => 'アップロードされたすべての文書に必須承認者として追加されるグループです。',
'settings_globalGroupReviewer' => '全文書のグループレビュアーを追加',
'settings_globalGroupReviewer_desc' => 'アップロードされたすべての文書に必須レビュアーとして追加されるグループです。',
'settings_globalReviewer' => '全文書のレビュアーを追加',
'settings_globalReviewer_desc' => 'アップロードされたすべての文書に必須レビュアーとして追加されるユーザーです。',
'settings_global_approver_is_admin' => '全文書の承認者「[login]」は管理者ですが、管理者は承認できません。',
'settings_global_reviewer_is_admin' => '全文書のレビュアー「[login]」は管理者ですが、管理者はレビューできません。',
'settings_guestID' => 'ゲストユーザー',
'settings_guestID_desc' => 'ゲストログイン時に使用するゲストユーザーのID（通常変更不要）',
'settings_guestid_is_admin' => 'ゲストユーザーが管理者です',
'settings_guestid_is_disabled' => 'ゲストユーザーは無効です',
'settings_httpRoot' => 'HTTPルート',
'settings_httpRoot_desc' => 'ドメイン部分の後のURL相対パス。http://やホスト名は含めないでください。例：URLが http://www.example.com/seeddms/ の場合、\'/seeddms/\' を設定。URLが http://www.example.com/ の場合、\'/\' を設定。',
'settings_incItemsPerPage' => 'ページ末尾で読み込む項目数',
'settings_incItemsPerPage_desc' => 'フォルダや文書数に制限がある場合、ページ下部までスクロールした際に追加で読み込むオブジェクト数を設定します。0に設定すると初回と同じ数が読み込まれます。',
'settings_initialDocumentStatus' => '文書の初期ステータス',
'settings_initialDocumentStatus_desc' => '文書追加時に設定されるステータス。',
'settings_initialDocumentStatus_draft' => '下書き',
'settings_initialDocumentStatus_released' => '公開',
'settings_inlineEditing' => 'インライン編集',
'settings_inlineEditing_desc' => '有効にすると、詳細ページ上で文書名を直接編集可能です。',
'settings_installADOdb' => 'ADOdbをインストール',
'settings_install_disabled' => 'ENABLE_INSTALL_TOOLファイルが削除されました。SeedDMSにログインして追加設定可能です。',
'settings_install_pear_package_log' => 'Pearパッケージ「Log」をインストール',
'settings_install_pear_package_webdav' => 'WebDAVインターフェースを使用する場合、Pearパッケージ「HTTP_WebDAV_Server」をインストール',
'settings_install_success' => 'インストールが正常に完了しました。',
'settings_install_welcome_text' => '<p>SeedDMSをインストールする前に、設定ディレクトリに\'ENABLE_INSTALL_TOOL\'ファイルを作成してください。作成していない場合、インストールは失敗します。Unixの場合は\'touch conf/ENABLE_INSTALL_TOOL\'で作成可能です。インストール完了後、このファイルを削除してください。</p><p>SeedDMSは最小限の要件で動作します。MySQLまたはSQLiteサポート、PHP有効なWebサーバが必要です。Log Pearパッケージのインストールも必要です。Lucene全文検索を使用する場合、Zend FrameworkをPHPから参照可能な場所にインストールしてください。WebDAVサーバを使用する場合はHTTP_WebDAV_Serverも必要です。パスはインストール時に設定可能です。</p><p>インストール前にデータベースを作成する場合は、手動で作成し、必要に応じてユーザーを作成し、設定ディレクトリ内のダンプをインポートしてください。インストールスクリプトでも作成可能ですが、十分な権限が必要です。</p>',
'settings_install_welcome_title' => 'SeedDMSインストールへようこそ',
'settings_install_zendframework' => 'Zendベースの全文検索エンジンを使用する場合、Zend Frameworkをインストールしてください。使用しない場合は無視してインストールを続行。',
'settings_invalid_guestid' => '無効なゲストユーザー',
'settings_language' => 'デフォルト言語',
'settings_language_desc' => 'デフォルト言語（"languages"フォルダ内のサブフォルダ名）',
'settings_libraryFolder' => 'ライブラリフォルダ',
'settings_libraryFolder_desc' => '新しい文書作成時にコピー元として使用されるフォルダ。',
'settings_logFileEnable' => 'ログファイルを有効化',
'settings_logFileEnable_desc' => 'ログファイルの有効/無効',
'settings_logFileMaxLevel' => '最大ログレベル',
'settings_logFileMaxLevel_desc' => 'このレベルまでのメッセージをログに記録',
'settings_logFileRestApiMaxLevel' => 'Rest API最大ログレベル',
'settings_logFileRestApiMaxLevel_desc' => 'Rest APIのこのレベルまでのメッセージをログに記録',
'settings_logFileRotation' => 'ログファイルローテーション',
'settings_logFileRotation_desc' => 'ログファイルのローテーション設定',
'settings_loginFailure' => 'ログイン失敗',
'settings_loginFailure_desc' => 'n回のログイン失敗後にアカウントを無効化',
'settings_logLevelAlert' => 'アラート',
'settings_logLevelCritical' => '重大',
'settings_logLevelDebug' => 'デバッグ',
'settings_logLevelEmergency' => '緊急',
'settings_logLevelError' => 'エラー',
'settings_logLevelInfo' => '情報',
'settings_logLevelNotice' => '通知',
'settings_logLevelWarning' => '警告',
'settings_luceneClassDir' => 'Lucene SeedDMSディレクトリ',
'settings_luceneClassDir_desc' => 'SeedDMS_Luceneへのパス（任意）。PHPから参照可能な場所にインストール済みの場合は空欄で可。',
'settings_luceneDir' => '全文検索インデックスディレクトリ',
'settings_luceneDir_desc' => 'Luceneインデックスのパス',
'settings_manager_approver_is_admin' => 'マネージャは管理者で必須承認者ですが、管理者は承認できません。',
'settings_manager_reviewer_is_admin' => 'マネージャは管理者で必須レビュアーですが、管理者はレビューできません。',
'settings_markdownComments' => 'コメントをMarkdownとして解析',
'settings_markdownComments_desc' => 'フォルダ、文書、バージョンのコメントをMarkdownとして解釈する場合に有効化。',
'settings_maxDirID' => '最大ディレクトリID',
'settings_maxDirID_desc' => '親ディレクトリあたりの最大サブディレクトリ数。知識がない場合は変更しないでください。デフォルト: 0',
'settings_maxExecutionTime' => '最大実行時間（秒）',
'settings_maxExecutionTime_desc' => 'スクリプトが終了されるまでの最大実行時間（秒）を設定',
'settings_maxItemsPerPage' => 'ページあたりの最大項目数',
'settings_maxItemsPerPage_desc' => 'フォルダ表示ページに表示されるフォルダや文書の数を制限。0に設定するとすべて表示。',
'settings_maxRecursiveCount' => '再帰的文書/フォルダ数の最大',
'settings_maxRecursiveCount_desc' => 'アクセス権を確認する際の最大文書/フォルダ数。超えた場合、フォルダ表示内の数は推定値となります。',
'settings_maxSizeForFullText' => 'インデックス対象の最大ファイルサイズ',
'settings_maxSizeForFullText_desc' => '設定サイズ以下の文書バージョンはアップロード直後に全文インデックス化されます。それ以外はメタデータのみ。',
'settings_maxUploadSize' => 'アップロード可能な最大ファイルサイズ',
'settings_maxUploadSize_desc' => '文書バージョンや添付ファイルに適用される最大サイズ。',
'settings_more_settings' => 'その他の設定を構成（デフォルトログイン: admin/admin）',
'settings_noDocumentFormFields' => 'このフィールドを非表示（文書）',
'settings_noDocumentFormFields_desc' => '文書追加/編集時に非表示。既存値は保持されます。',
'settings_noFolderFormFields' => 'このフィールドを非表示（フォルダ）',
'settings_noFolderFormFields_desc' => 'フォルダ追加/編集時に非表示。既存値は保持されます。',
'settings_notfound' => '見つかりません',
'settings_Notification' => '通知設定',
'settings_notwritable' => '設定ファイルに書き込みできないため保存できません。',
'settings_no_content_dir' => 'コンテンツディレクトリ',
'settings_onePageMode' => 'ワンページモード',
'settings_onePageMode_desc' => 'フォルダやソート変更時にページをリロードせずリストやナビゲーションを更新します。',
'settings_overrideMimeType' => 'MimeTypeを上書き',
'settings_overrideMimeType_desc' => 'アップロード時にブラウザ提供のMimeTypeをSeedDMSで判定したMimeTypeに上書き。',
'settings_overrideTheme' => 'テーマを上書き',
'settings_overrideTheme_desc' => 'ユーザーのテーマ設定をこの設定で上書きします。',
'settings_partitionSize' => '分割ファイルサイズ',
'settings_partitionSize_desc' => 'Jumploaderでアップロードされる分割ファイルのサイズ（バイト）。サーバ設定の最大アップロードサイズを超えないこと。',
'settings_passwordExpiration' => 'パスワード有効期限',
'settings_passwordExpiration_desc' => 'パスワードが期限切れとなりリセットが必要になる日数。0で無効。',
'settings_passwordHistory' => 'パスワード履歴',
'settings_passwordHistory_desc' => '再利用できるまでの過去使用パスワード数。0で無効。',
'settings_passwordStrength' => '最低パスワード強度',
'settings_passwordStrengthAlgorithm' => 'パスワード強度のアルゴリズム',
'settings_passwordStrengthAlgorithm_desc' => '強度計算に使用するアルゴリズム。「simple」は8文字以上、小文字、大文字、数字、特殊文字を確認し、条件を満たすと100点、満たさないと0点。',
'settings_passwordStrengthAlgorithm_valadvanced' => '高度',
'settings_passwordStrengthAlgorithm_valsimple' => '簡易',
'settings_passwordStrength_desc' => '最低パスワード強度（0〜100）。0にするとチェック無効。',
'settings_pear_log' => 'Pearパッケージ: Log',
'settings_pear_webdav' => 'Pearパッケージ: HTTP_WebDAV_Server',
'settings_perms' => '権限',
'settings_php_dbDriver' => 'PHP拡張: php_（現在の値を確認）',
'settings_php_gd2' => 'PHP拡張: php_gd2',
'settings_php_mbstring' => 'PHP拡張: php_mbstring',
'settings_php_version' => 'PHPバージョン',
'settings_presetExpirationDate' => '事前設定の有効期限',
'settings_presetExpirationDate_desc' => 'アップロードされる新規文書の有効期限を設定。PHPのstrtotime()形式で指定可能（例: +5 weeks）。',
'settings_previewWidthDetail' => 'プレビュー画像幅（詳細）',
'settings_previewWidthDetail_desc' => '詳細ページに表示されるプレビュー画像の幅',
'settings_previewWidthDropFolderList' => 'プレビュー画像幅（ドロップフォルダリスト）',
'settings_previewWidthDropFolderList_desc' => 'ドロップフォルダ選択時のリストで表示されるプレビュー画像の幅',
'settings_previewWidthList' => 'プレビュー画像幅（リスト）',
'settings_previewWidthList_desc' => 'リスト表示のプレビュー画像幅',
'settings_previewWidthMenuList' => 'プレビュー画像幅（メニューリスト）',
'settings_previewWidthMenuList_desc' => 'ドロップフォルダメニューで表示されるプレビュー画像の幅',
'settings_printDisclaimer' => '免責事項を印刷',
'settings_printDisclaimer_desc' => '有効にすると、全ページ下部に免責事項が印刷されます。',
'settings_proxyUPassword' => 'プロキシパスワード',
'settings_proxyUPassword_desc' => 'プロキシ認証用パスワード',
'settings_proxyUrl' => 'プロキシURL',
'settings_proxyUrl_desc' => '拡張機能リポジトリにアクセスするためのプロキシURL',
'settings_proxyUser' => 'プロキシユーザー名',
'settings_proxyUser_desc' => 'プロキシ認証に使用するユーザー名',
'settings_quota' => 'ユーザーのディスク容量',
'settings_quota_desc' => 'ユーザーが使用可能な最大ディスク容量（バイト）。0で無制限。ユーザーごとに上書き可能。',
'settings_removeFromDropFolder' => 'アップロード成功後にドロップフォルダから削除',
'settings_removeFromDropFolder_desc' => 'ドロップフォルダから取得したファイルをアップロード後に削除する場合、有効化',
'settings_repositoryUrl' => 'リポジトリURL',
'settings_repositoryUrl_desc' => '拡張機能リポジトリのURL',
'settings_restricted' => '制限付きアクセス',
'settings_restricted_desc' => 'ローカルデータベースに登録があるユーザーのみログインを許可（LDAP認証に関係なく）',
'settings_rootDir' => 'ルートディレクトリ',
'settings_rootDir_desc' => 'SeedDMSが設置されているパス',
'settings_rootFolderID' => 'ルートフォルダID',
'settings_rootFolderID_desc' => 'ルートフォルダのID（通常変更不要）',
'settings_SaveError' => '設定ファイル保存エラー',
'settings_Server' => 'サーバ設定',
'settings_showFullPreview' => '文書を完全表示',
'settings_showFullPreview_desc' => 'ブラウザが対応している場合、詳細ページで文書の完全プレビューを有効/無効',
'settings_showMissingTranslations' => '翻訳欠損を表示',
'settings_showMissingTranslations_desc' => 'ページ下部に欠損翻訳をリスト表示。ログインユーザーは提案を提出可能。運用環境では無効推奨。',
'settings_showSingleSearchHit' => '検索結果が1件の場合は直接表示',
'settings_showSingleSearchHit_desc' => '検索結果が1件のみの場合、結果一覧ではなくその文書を直接表示',
'settings_Site' => 'サイト',
'settings_siteDefaultPage' => 'サイトのデフォルトページ',
'settings_siteDefaultPage_desc' => 'ログイン時のデフォルトページ。空欄の場合は out/out.ViewFolder.php',
'settings_siteName' => 'サイト名',
'settings_siteName_desc' => 'ページタイトルに使用されるサイト名。デフォルト: SeedDMS',
'settings_SMTP' => 'SMTPサーバ設定',
'settings_smtpForceFrom' => '送信元メールを強制',
'settings_smtpForceFrom_desc' => '全メールで「送信元」アドレスを使用',
'settings_smtpLazySSL' => 'SSLチェックを緩める',
'settings_smtpLazySSL_desc' => '自己署名証明書や期限切れ証明書を使用する場合、SSLチェックを無効化。リスクに注意。',
'settings_smtpPassword' => 'SMTPサーバパスワード',
'settings_smtpPassword_desc' => 'SMTPサーバパスワード',
'settings_smtpPort' => 'SMTPサーバポート',
'settings_smtpPort_desc' => 'SMTPサーバポート（デフォルト:25）',
'settings_smtpSendFrom' => '送信元',
'settings_smtpSendFrom_desc' => '送信元アドレス',
'settings_smtpSendTestMail' => 'テストメール送信',
'settings_smtpSendTestMail_desc' => '現在のメール設定を確認するためのテストメールを送信',
'settings_smtpServer' => 'SMTPサーバホスト名',
'settings_smtpServer_desc' => 'SMTPサーバのホスト名',
'settings_smtpUser' => 'SMTPサーバユーザー',
'settings_smtpUser_desc' => 'SMTPサーバのユーザー名',
'settings_sortFoldersDefault' => 'フォルダのデフォルトソート方法',
'settings_sortFoldersDefault_desc' => 'フォルダ表示のソート方法を設定',
'settings_sortFoldersDefault_val_name' => '名前順',
'settings_sortFoldersDefault_val_sequence' => '順序順',
'settings_sortFoldersDefault_val_unsorted' => '未ソート',
'settings_sortUsersInList' => 'ユーザーリストの並び順',
'settings_sortUsersInList_desc' => '選択メニュー内のユーザーをログイン名かフルネームで並べる',
'settings_sortUsersInList_val_fullname' => 'フルネーム順',
'settings_sortUsersInList_val_login' => 'ログイン順',
'settings_stagingDir' => '分割アップロードディレクトリ',
'settings_stagingDir_desc' => 'Jumploaderが分割アップロードしたファイルを結合する前の一時ディレクトリ',
'settings_start_install' => 'インストール開始',
'settings_stopWordsFile' => 'ストップワードファイルのパス',
'settings_stopWordsFile_desc' => '全文検索を有効にした場合、インデックス化しない単語を記載',
'settings_strictFormCheck' => '厳密なフォームチェック',
'settings_strictFormCheck_desc' => 'trueの場合、全フィールドが値を持つかチェック。falseの場合、コメントやキーワードは任意。レビューやステータス上書き時はコメント必須。',
'settings_suggestionvalue' => 'サジェスト値',
'settings_suggestTerms' => '検索語サジェスト',
'settings_suggestTerms_desc' => '有効にすると、検索欄で文書やフォルダだけでなく検索候補も表示',
'settings_System' => 'システム',
'settings_tasksInMenu' => 'メニュー内タスク',
'settings_tasksInMenu_approval' => '承認',
'settings_tasksInMenu_checkedout' => 'チェックアウト中',
'settings_tasksInMenu_desc' => 'カウントするタスクを選択。未選択の場合はすべてカウント',
'settings_tasksInMenu_needscorrection' => '修正が必要',
'settings_tasksInMenu_receipt' => '受領',
'settings_tasksInMenu_rejected' => '却下',
'settings_tasksInMenu_review' => 'レビュー',
'settings_tasksInMenu_revision' => '改訂',
'settings_tasksInMenu_workflow' => 'ワークフロー',
'settings_theme' => 'デフォルトテーマ',
'settings_theme_desc' => 'デフォルトスタイル（"styles"フォルダ内のサブフォルダ名）',
'settings_titleDisplayHack' => 'タイトル表示ハック',
'settings_titleDisplayHack_desc' => 'ページタイトルが2行以上になる場合の回避策',
'settings_undelUserIds' => '削除不可ユーザーID',
'settings_undelUserIds_desc' => '削除できないユーザーIDをカンマ区切りで指定',
'settings_updateDatabase' => 'データベーススキーマ更新スクリプトを実行',
'settings_updateNotifyTime' => '更新通知時間',
'settings_updateNotifyTime_desc' => 'ユーザーに通知する文書変更の範囲（秒）',
'settings_upgrade_php' => 'PHPをバージョン5.6.38以上にアップグレード',
'settings_uploadedAttachmentIsPublic' => '新規添付ファイルは公開',
'settings_uploadedAttachmentIsPublic_desc' => 'フォームやドラッグ&ドロップでアップロードされた添付ファイルはデフォルトで公開',
'settings_useHomeAsRootFolder' => 'ホームフォルダをルートとして使用',
'settings_useHomeAsRootFolder_desc' => 'ユーザーのホームフォルダ（管理者除く）をルートフォルダとして使用（実験的）',
'settings_versioningFileName' => 'バージョニングファイル名',
'settings_versioningFileName_desc' => 'バックアップツールが作成するバージョン情報ファイルの名前',
'settings_versiontolow' => 'バージョンが低すぎます',
'settings_viewOnlineFileTypes' => 'オンライン閲覧可能なファイルタイプ',
'settings_viewOnlineFileTypes_desc' => '以下の拡張子を持つファイルをオンラインで表示可能（小文字のみ）',
'settings_webdav' => 'WebDAV',
'settings_workflowMode' => 'ワークフローモード',
'settings_workflowMode_desc' => '高度なワークフローを使用すると、文書バージョンの独自リリースフローを指定可能。',
'settings_workflowMode_valadvanced' => '高度',
'settings_workflowMode_valnone' => 'なし',
'settings_workflowMode_valtraditional' => '従来型',
'settings_workflowMode_valtraditional_only_approval' => '従来型（レビューなし）',
'settings_zendframework' => 'Zend Framework',
'set_expiration_date_help' => '文書の有効期限は日付の開始時に切れます。',
'set_expiry' => '有効期限を設定',
'set_owner' => '所有者を設定',
'set_owner_error' => '所有者の設定中にエラーが発生',
'set_password' => 'パスワードを設定',
'set_workflow' => 'ワークフローを設定',
'show_extension_changelog' => '変更履歴を表示',
'show_extension_readme' => 'Readmeを表示',
'show_extension_version_list' => 'バージョン一覧を表示',
'signed_in_as' => 'ログイン中:',
'sign_in' => 'ログイン',
'sign_out' => 'ログアウト',
'sign_out_user' => 'ユーザーをログアウト',
'site_brand' => '',
'skip_default_export_cols' => 'デフォルト列をスキップ',
'sk_SK' => 'スロバキア語',
'sort_by_date' => '日付順に並べ替え',
'sort_by_expiration_date' => '有効期限順に並べ替え',
'sort_by_name' => '名前順に並べ替え',
'sort_by_sequence' => '順序順に並べ替え',
'space_used_on_data_folder' => 'データフォルダ使用容量',
'splash_added_to_clipboard' => 'クリップボードに追加',
'splash_add_access' => '新しいアクセス権を追加',
'splash_add_attribute' => '新しい属性を追加',
'splash_add_category' => '新しいカテゴリを追加',
'splash_add_group' => '新しいグループを追加',
'splash_add_group_member' => '新しいグループメンバーを追加',
'splash_add_keyword' => '新しいキーワードを追加',
'splash_add_keyword_category' => '新しいキーワードリストを追加',
'splash_add_notify' => '新しい通知を追加',
'splash_add_role' => '新しいロールを追加',
'splash_add_task' => '新しいタスクを追加',
'splash_add_to_transmittal' => '送付状に追加',
'splash_add_transmittal' => '新しい送付状を追加',
'splash_add_user' => '新しいユーザーを追加',
'splash_cancel_checkout' => 'チェックアウトをキャンセル',
'splash_checked_in' => '文書がチェックインされました',
'splash_cleared_cache' => 'キャッシュをクリアしました',
'splash_cleared_clipboard' => 'クリップボードをクリアしました',
'splash_delete_access' => 'アクセス権を削除',
'splash_document_added' => '文書を追加',
'splash_document_checkedout' => '文書をチェックアウト',
'splash_document_deleted' => '文書を削除',
'splash_document_edited' => '文書を保存',
'splash_document_indexed' => '文書 \'[name]\' をインデックス化',
'splash_document_locked' => '文書をロック',
'splash_document_name_changed' => '文書名を変更',
'splash_document_unlocked' => '文書のロックを解除',
'splash_document_updated' => '文書を更新',
'splash_edit_access' => 'アクセス権を変更',
'splash_edit_attribute' => '属性を保存',
'splash_edit_category' => 'カテゴリを保存',
'splash_edit_event' => 'イベントを保存',
'splash_edit_group' => 'グループを保存',
'splash_edit_keyword' => 'キーワードを保存',
'splash_edit_keyword_category' => 'キーワードリスト名を変更',
'splash_edit_role' => 'ロールを保存',
'splash_edit_task' => 'タスクを保存',
'splash_edit_transmittal' => '送付状を保存',
'splash_edit_user' => 'ユーザーを保存',
'splash_error_add_to_transmittal' => '文書を送付状に追加中にエラー',
'splash_error_checkin_ended' => 'チェックインを終了し、変更を破棄',
'splash_error_rm_download_link' => 'ダウンロードリンク削除時にエラー',
'splash_error_saving_file' => 'ファイル保存中にエラー',
'splash_error_send_download_link' => 'ダウンロードリンク送信中にエラー',
'splash_expiration_date_cleared' => '有効期限をクリア',
'splash_expiration_date_set' => '有効期限を [date] に設定',
'splash_extension_getlist' => 'リポジトリから拡張機能リストを更新',
'splash_extension_import' => '拡張機能をインストール',
'splash_extension_refresh' => '拡張機能リストを更新',
'splash_extension_upload' => '拡張機能をインストール',
'splash_folder_added' => 'フォルダを追加',
'splash_folder_deleted' => 'フォルダを削除',
'splash_folder_edited' => 'フォルダ変更を保存',
'splash_importfs' => '[docs] 件の文書と [folders] 件のフォルダをインポート',
'splash_inherit_access' => 'アクセス権が継承されます',
'splash_invalid_folder_id' => '無効なフォルダID',
'splash_invalid_searchterm' => '無効な検索語',
'splash_invalid_search_service' => '無効な検索サービス',
'splash_link_document' => 'リンクを追加',
'splash_mimetype_changed' => 'Mimetypeを変更しました',
'splash_moved_clipboard' => 'クリップボードを現在のフォルダに移動',
'splash_move_document' => '文書を移動',
'splash_move_folder' => 'フォルダを移動',
'splash_notinherit_access' => 'アクセス権の継承を解除',
'splash_orig_filename_changed' => '元のファイル名を変更',
'splash_receipt_update_success' => '受領を正常に追加',
'splash_removed_from_clipboard' => 'クリップボードから削除',
'splash_rm_attribute' => '属性を削除',
'splash_rm_attr_value' => '属性値を削除',
'splash_rm_category' => 'カテゴリを削除',
'splash_rm_document' => '文書を削除',
'splash_rm_download_link' => 'ダウンロードリンクを削除',
'splash_rm_folder' => 'フォルダを削除',
'splash_rm_group' => 'グループを削除',
'splash_rm_group_member' => 'グループメンバーを削除',
'splash_rm_keyword' => 'キーワードを削除',
'splash_rm_keyword_category' => 'キーワードリストを削除',
'splash_rm_notify' => '通知を削除',
'splash_rm_role' => 'ロールを削除',
'splash_rm_transmittal' => '送付状を削除',
'splash_rm_user' => 'ユーザーを削除',
'splash_rm_user_processes' => 'ユーザーをすべてのプロセスから削除',
'splash_rm_workflow' => 'ワークフローを削除',
'splash_rm_workflow_action' => 'ワークフローアクションを削除',
'splash_rm_workflow_state' => 'ワークフローステートを削除',
'splash_saved_file' => 'バージョンを保存',
'splash_save_user_data' => 'ユーザーデータを保存',
'splash_send_download_link' => 'ダウンロードリンクをメール送信しました',
'splash_send_login_data' => 'ログイン情報を送信',
'splash_setowner' => '新しい所有者を設定',
'splash_settings_saved' => '設定を保存',
'splash_set_default_access' => 'デフォルトアクセス権を設定',
'splash_substituted_user' => 'ユーザーを切り替えました',
'splash_switched_back_user' => '元のユーザーに戻しました',
'splash_toogle_group_manager' => 'グループマネージャを切り替え',
'splash_transfer_content' => 'コンテンツを転送',
'splash_transfer_document' => '文書を転送',
'splash_transfer_objects' => 'オブジェクトを転送',
'splash_trigger_workflow' => 'ワークフロー遷移を実行',
'startdate' => '開始日',
'state_and_next_state' => '現在/次の状態',
'statistic' => '統計',
'statistics_mail_subject' => '統計情報',
'status' => 'ステータス',
'status_approval_rejected' => '却下',
'status_approved' => '承認済み',
'status_approver_removed' => '承認者をプロセスから削除',
'status_change' => 'ステータス変更',
'status_needs_correction' => '修正が必要',
'status_not_approved' => '未承認',
'status_not_receipted' => '未受領',
'status_not_reviewed' => '未レビュー',
'status_not_revised' => '未改訂',
'status_receipted' => '受領済み',
'status_receipt_rejected' => '受領拒否',
'status_recipient_removed' => '受信者をリストから削除',
'status_reviewed' => 'レビュー済み',
'status_reviewer_rejected' => '却下',
'status_reviewer_removed' => 'レビュアーをプロセスから削除',
'status_revised' => '改訂済み',
'status_revision_rejected' => '改訂拒否',
'status_revision_sleeping' => '保留中',
'status_revisor_removed' => '改訂者をリストから削除',
'status_unknown' => '不明',
'storage' => 'ストレージ',
'storage_size' => 'ストレージ容量',
'subfolder_duplicate_name' => 'サブフォルダ名が重複しています',
'submit_2_fact_auth' => '秘密を保存',
'submit_approval' => '承認を送信',
'submit_login' => 'ログイン',
'submit_password' => '新しいパスワードを設定',
'submit_password_forgotten' => '手続きを開始',
'submit_receipt' => '受領を送信',
'submit_review' => 'レビューを送信',
'submit_revision' => '改訂を追加',
'submit_userinfo' => '情報を送信',
'submit_webauthn_login' => 'WebAuthnでログイン',
'submit_webauthn_register' => '登録',
'subsribe_timelinefeed' => 'タイムラインフィードを購読',
'substitute_to_user' => '\'[username]\' に切り替え',
'substitute_user' => 'ユーザーを切り替え',
'success_add_aro' => 'アクセスリクエストオブジェクトを追加',
'success_add_permission' => '権限を追加',
'success_remove_permission' => '権限を削除',
'success_toogle_permission' => '権限を変更',
'sunday' => '日曜日',
'sunday_abbr' => '日',
'sv_SE' => 'スウェーデン語',
'switched_to' => '切り替えました',
'takeOverAttributeValue' => '前バージョンから属性値を引き継ぐ',
'takeOverGrpApprover' => '前バージョンから承認者グループを引き継ぐ',
'takeOverGrpApprovers' => '承認者グループを引き継ぐ',
'takeOverGrpReviewer' => '前バージョンからレビュアーグループを引き継ぐ',
'takeOverGrpReviewers' => 'レビュアーグループを引き継ぐ',
'takeOverIndApprover' => '前バージョンから個別承認者を引き継ぐ',
'takeOverIndApprovers' => '個別承認者を引き継ぐ',
'takeOverIndReviewer' => '前バージョンから個別レビュアーを引き継ぐ',
'takeOverIndReviewers' => '個別レビュアーを引き継ぐ',
'target_equals_source_folder' => '対象フォルダは元のフォルダと同じです',
'tasks' => 'タスク',
'task_core_expireddocs_days' => '日数',
'task_core_expireddocs_dryrun' => 'テスト実行',
'task_core_expireddocs_email' => 'メール',
'task_core_expireddocs_peruser' => 'ユーザーごと',
'task_core_importdropfolder_dryrun' => 'テスト実行',
'task_core_importdropfolder_dryrun_desc' => '有効にすると、ドロップフォルダ内のファイルはインポートされ削除されませんが、すべての操作はログに記録されます。',
'task_core_importdropfolder_keepfile' => 'ドロップフォルダにファイルを残す',
'task_core_importdropfolder_keepfile_desc' => '有効にすると、インポートされたファイルはドロップフォルダから削除されません。',
'task_core_importdropfolder_recursive' => '再帰的',
'task_core_importdropfolder_targetfolder' => '対象フォルダ',
'task_core_importdropfolder_targetfolder_desc' => 'ドロップフォルダ内のファイルはこのSeedDMSフォルダにインポートされます。',
'task_core_importdropfolder_users' => 'ユーザー',
'task_core_indexingdocs_recreate' => 'インデックスを再作成',
'task_core_recentchanges_days' => '日数',
'task_core_recentchanges_lists' => 'リスト',
'task_core_recentchanges_users' => 'ユーザー',
'task_core_statistic_users' => 'ユーザー',
'task_description' => '説明',
'task_disabled' => '無効',
'task_failures' => '失敗した実行',
'task_frequency' => '実行頻度',
'task_frequency_placeholder' => 'm h d m dow、または @daily、@hourly',
'task_last_run' => '最終実行',
'task_name' => '名前',
'task_next_run' => '次回実行',
'temp_jscode' => '一時的なJavaScriptコード',
'testmail_body' => 'このメールはSeedDMSのメール設定をテストするためのものです

URL: [url]
サイト名: [sitename]
バージョン: [version]
SMTPサーバー: [smtpserver]
SMTPポート: [smtpport]
SSLチェック無効: [lazyssl]
送信者使用: [forcefrom]',
'testmail_subject' => 'テストメール',
'theme' => 'テーマ',
'thursday' => '木曜日',
'thursday_abbr' => '木',
'timeline' => 'タイムライン',
'timeline_add_file' => '新しい添付ファイル',
'timeline_add_version' => '新しいバージョン [version]',
'timeline_full_add_file' => '[document]<br />新しい添付ファイル',
'timeline_full_add_version' => '[document]<br />新しいバージョン [version]',
'timeline_full_scheduled_revision' => '[document]<br />バージョン [version] の改訂',
'timeline_full_status_change' => '[document]<br />バージョン [version]: [status]',
'timeline_scheduled_revision' => 'バージョン [version] の改訂',
'timeline_selected_item' => '選択された文書',
'timeline_skip_add_file' => '添付ファイルを追加',
'timeline_skip_scheduled_revision' => '予定された改訂',
'timeline_skip_status_change_-1' => '却下',
'timeline_skip_status_change_-2' => '廃止',
'timeline_skip_status_change_-3' => '期限切れ',
'timeline_skip_status_change_0' => 'レビュー待ち',
'timeline_skip_status_change_1' => '承認待ち',
'timeline_skip_status_change_2' => '公開済み',
'timeline_skip_status_change_3' => 'ワークフロー中',
'timeline_skip_status_change_4' => '改訂中',
'timeline_skip_status_change_5' => '草稿',
'timeline_status_change' => 'バージョン [version]: [status]',
'title' => 'タイトル',
'to' => '宛先',
'toggle_manager' => 'マネージャを切り替え',
'toggle_qrcode' => 'QRコードの表示/非表示',
'total' => '合計',
'to_before_from' => '終了日は開始日より前に設定できません',
'transfer_content' => 'コンテンツを転送',
'transfer_document' => '文書を転送',
'transfer_no_read_access' => 'ユーザーはフォルダの読み取り権限を持っていません',
'transfer_no_users' => '現在、文書を転送できるユーザーがいません。',
'transfer_no_write_access' => 'ユーザーはフォルダの書き込み権限を持っていません',
'transfer_objects' => 'オブジェクトを転送',
'transfer_objects_to_user' => '新しい所有者',
'transfer_processes_to_user' => 'プロセスをユーザーに転送',
'transfer_process_to_user' => 'プロセスをユーザーに転送',
'transfer_to_user' => 'ユーザーに転送',
'transition_triggered_email' => 'ワークフロー遷移が実行されました',
'transition_triggered_email_body' => 'ワークフロー遷移が実行されました

文書: [name]
バージョン: [version]
コメント: [comment]
ワークフロー: [workflow]
前の状態: [previous_state]
現在の状態: [current_state]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'transition_triggered_email_body_html' => '<p>ワークフロー遷移が実行されました</p>

<p>文書: [name]<br />
バージョン: [version]<br />
コメント: [comment]<br />
ワークフロー: [workflow]<br />
前の状態: [previous_state]<br />
現在の状態: [current_state]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'transition_triggered_email_subject' => '[sitename]: [name] - ワークフロー遷移が実行されました',
'transmittal' => '送付状',
'transmittalitem_removed' => '送付状アイテムを削除',
'transmittalitem_updated' => '文書を最新バージョンに更新',
'transmittals' => '送付状',
'transmittal_comment' => 'コメント',
'transmittal_name' => '名前',
'transmittal_size' => 'サイズ',
'tree_loading' => '文書ツリーを読み込み中です…',
'trigger_workflow' => 'ワークフロー',
'tr_TR' => 'トルコ語',
'tuesday' => '火曜日',
'tuesday_abbr' => '火',
'types_generic' => '汎用タイプ',
'type_of_hook' => 'タイプ',
'type_to_filter' => 'フィルターするタイプ',
'type_to_search' => '検索対象のタイプ',
'uk_UA' => 'ウクライナ語',
'undefined' => '未定義',
'under_folder' => 'フォルダ内',
'unknown_attrdef' => '不明な属性定義',
'unknown_command' => 'コマンドが認識されません。',
'unknown_document_category' => '不明なカテゴリ',
'unknown_group' => '不明なグループID',
'unknown_id' => '不明なID',
'unknown_keyword_category' => '不明なカテゴリ',
'unknown_owner' => '不明な所有者ID',
'unknown_status' => '不明なステータス',
'unknown_user' => '不明なユーザーID',
'unlinked_content' => 'リンクされていないコンテンツ',
'unlinked_documents' => 'リンクされていない文書',
'unlinked_folders' => 'リンクされていないフォルダ',
'unlinking_objects' => 'コンテンツのリンクを解除中',
'unlock_cause_access_mode_all' => 'アクセスモード「全て」があるため、更新可能です。ロックは自動的に解除されます。',
'unlock_cause_locking_user' => 'ロックした本人であるため、更新可能です。ロックは自動的に解除されます。',
'unlock_document' => 'ロック解除',
'update' => '更新',
'updated' => '更新済み',
'updated_documents' => '更新された文書',
'update_approvers' => '承認者リストを更新',
'update_document' => '文書を更新',
'update_fulltext_index' => '全文検索インデックスを更新',
'update_fulltext_messages' => 'メッセージ',
'update_info' => '更新情報',
'update_locked_msg' => 'この文書はロックされています。',
'update_recipients' => '受信者リストを更新',
'update_reviewers' => 'レビュアーリストを更新',
'update_revisors' => '改訂者リストを更新',
'update_transmittalitem' => '最新バージョンに更新',
'uploaded_by' => 'アップロード者',
'uploading_failed' => 'ファイルのアップロードに失敗しました。最大アップロードサイズを確認してください。',
'uploading_maxsize' => 'アップロードされたファイルが最大サイズを超えています。',
'uploading_postmaxsize' => 'POSTリクエストが最大サイズを超えています。',
'uploading_zerosize' => '空のファイルをアップロードしています。アップロードを中止しました。',
'used_discspace' => '使用済みディスク容量',
'user' => 'ユーザー',
'userdata_file' => 'ユーザーデータファイル',
'userid_groupid' => 'ユーザーID/グループID',
'users' => 'ユーザー',
'users_and_groups' => 'ユーザー/グループ',
'users_done_work' => '作業完了ユーザー',
'user_exists' => 'ユーザーは既に存在します。',
'user_group' => 'ユーザー/グループ',
'user_group_management' => 'ユーザー/グループ管理',
'user_image' => '画像',
'user_info' => 'ユーザー情報',
'user_is_mandatory_approver' => 'ユーザーは必須承認者です',
'user_is_mandatory_reviewer' => 'ユーザーは必須レビュアーです',
'user_list' => 'ユーザーリスト',
'user_login' => 'ユーザーID',
'user_management' => 'ユーザー管理',
'user_name' => '氏名',
'user_previously_removed_from_approvers' => 'ユーザーは以前に承認者から削除されました。',
'user_previously_removed_from_recipients' => 'ユーザーは以前に改訂者から削除されました。',
'user_previously_removed_from_reviewers' => 'ユーザーは以前にレビュアーから削除されました。',
'user_previously_removed_from_revisors' => 'ユーザーは以前に改訂者から削除されました。',
'use_comment_of_document' => '文書のコメントを使用',
'use_default_categories' => '既定のカテゴリを使用',
'use_default_keywords' => '既定のキーワードを使用',
'valid_till' => '有効期限',
'version' => 'バージョン',
'versioning_file_creation' => 'バージョン情報ファイル作成',
'versioning_file_creation_warning' => 'この操作により、各文書のバージョン情報を含むファイルが作成されます。作成後、各ファイルは文書フォルダ内に保存されます。これらのファイルは通常のDMS運用には不要ですが、リポジトリ全体を他システムに移行する場合に有用です。',
'versioning_info' => 'バージョン情報',
'versiontolow' => 'バージョンが低すぎます',
'version_comment' => 'バージョンコメント',
'version_comment_changed_email_body' => 'コメントが変更されました

文書: [name]
バージョン: [version]
以前のコメント: [old_comment]
新しいコメント: [new_comment]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'version_comment_changed_email_body_html' => '<p>コメントが変更されました</p>

<p>文書: [name]<br />
バージョン: [version]<br />
以前のコメント: [old_comment]<br />
新しいコメント: [new_comment]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'version_comment_changed_email_subject' => '[sitename]: [name] - コメントが変更されました',
'version_deleted_email' => 'バージョンが削除されました',
'version_deleted_email_body' => 'バージョンが削除されました

文書: [name]
バージョン: [version]
親フォルダ: [folder_path]
ユーザー: [username]
URL: [url]',
'version_deleted_email_body_html' => '<p>バージョンが削除されました</p>

<p>文書: [name]<br />
バージョン: [version]<br />
親フォルダ: [folder_path]<br />
ユーザー: [username]<br />
URL: [url]</p>',
'version_deleted_email_subject' => '[sitename]: [name] - バージョンが削除されました',
'version_info' => 'バージョン情報',
'view' => '表示',
'view_document' => '文書詳細を表示',
'view_folder' => 'フォルダ詳細を表示',
'view_online' => 'オンライン表示',
'warning' => '警告',
'warning_remove_approval_log' => '単一の承認を削除すると元に戻せず、報告もされません。レビュアーは再度レビューを行う必要があります。',
'warning_remove_review_log' => '単一のレビューを削除すると元に戻せず、報告もされません。レビュアーは再度レビューを行う必要があります。',
'webauthn' => 'WebAuthn',
'webauthn_auth' => 'WebAuthn認証',
'webauthn_crossplatform_info' => '取り外し可能なデバイス（Yubicoキー等）を使って複数のPCでログインする場合は「Yes」を、PCに接続されたデバイスを使用する場合は「No」を選択します。この設定はブラウザやOSが提示するデバイスに影響します。',
'webauthn_info' => 'WebAuthnは公開鍵暗号を用いたパスワード不要の認証です。ウェブサイトごとに秘密鍵と公開鍵のペア（クレデンシャル）が作成されます。秘密鍵はユーザーのデバイスに安全に保存され、公開鍵とランダム生成されたIDがサーバに保存されます。サーバはこの公開鍵を用いてユーザーの本人確認を行います。秘密鍵は通常ハードウェアトークンに保存されます。認証に使用するには事前登録が必要です。',
'webauthn_login_test' => 'ログインテスト',
'webauthn_registration' => '登録',
'webauth_crossplatform' => 'クロスプラットフォーム',
'wednesday' => '水曜日',
'wednesday_abbr' => '水',
'weeks' => '週',
'week_view' => '週表示',
'workflow' => 'ワークフロー',
'workflows_involded' => '関与しているワークフロー',
'workflow_actions_management' => 'ワークフローアクション管理',
'workflow_action_in_use' => 'このアクションは現在ワークフローで使用されています。',
'workflow_action_name' => '名前',
'workflow_editor' => 'ワークフローエディタ',
'workflow_group_summary' => 'グループ概要',
'workflow_has_cycle' => 'ワークフローに循環があります',
'workflow_initstate' => '初期状態',
'workflow_in_use' => 'このワークフローは現在文書で使用されています。',
'workflow_layoutdata_saved' => 'レイアウトデータを保存しました',
'workflow_log' => 'ワークフロープロトコル',
'workflow_management' => 'ワークフロー管理',
'workflow_name' => '名前',
'workflow_no_doc_rejected_state' => 'ワークフロー状態で文書は却下されません！',
'workflow_no_doc_released_state' => 'ワークフロー状態で文書は公開されません！',
'workflow_no_initial_state' => '遷移のいずれもワークフローの初期状態から始まっていません！',
'workflow_no_states' => 'ワークフローを追加する前に、まず状態を定義してください。',
'workflow_save_layout' => 'レイアウトを保存',
'workflow_state' => 'ワークフロー状態',
'workflow_states_management' => 'ワークフロー状態管理',
'workflow_state_docstatus' => '文書ステータス',
'workflow_state_in_use' => 'この状態は現在ワークフローで使用されています。',
'workflow_state_name' => '名前',
'workflow_summary' => 'ワークフロー概要',
'workflow_title' => '',
'workflow_transition_without_user_group' => '少なくとも1つの遷移にユーザーもグループも設定されていません！',
'workflow_user_summary' => 'ユーザー概要',
'wrong_checksum' => 'チェックサムが間違っています',
'wrong_filetype' => 'ファイルタイプが間違っています',
'x_more_objects' => '[number] 件のオブジェクトが追加であります',
'year_view' => '年表示',
'yes' => 'はい',
'zh_CN' => '中国語（簡体）',
'zh_TW' => '中国語（繁体）',
);
?>
